### ISSUE TITLE
Can not resolve a node from static nodes in cluster

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1094]
# Problem

In `cluster.go` we have a node: `enode://a6a2a9b3a7cbb0a15da74301537ebba549c990e3325ae78e1272a19a3ace150d03c184b8ac86cc33f1f2f63691e467d49308f02d613277754c4dccd6773b95e8@206.189.108.68:30304`. 

It can't be resolve:
```
DEBUG[07-12|12:41:42] Resolving node failed                    id=a6a2a9b3a7cbb0a1 newdelay=4m0s
```

# Implementation

Debug why it is so and if the enode is incorrect, replace it with a correct one.

# Acceptance Criteria

All static nodes in `mainnetCluster` and `ropstenCluster` can be resolved.

**Comment by jakubgs** [comment]
Oh yeah, this is caused by me replacing all DigitalOcean hosts like 2 weeks ago. This config file is using a droplet IP rather than a floating IP, so when the host got replaced the IP became useless.

The config file should be updated with any enode from any host from:
https://consul.status.im/ui/do-ams3/services/statusd-whisper?s=eth.beta

I'll make a PR to update this.

<blockquote><div><strong><a href="https://consul.status.im/ui/do-ams3/services/statusd-whisper?s=eth.beta">Sign In</a></strong></div></blockquote>

**Comment by jakubgs** [comment]
Here's the fix: https://github.com/status-im/status-go/pull/1095
