### ISSUE TITLE
"Error: transaction has been discarded" when deploying a contract

### ISSUE THREAD

**Issue by morelazers** [status-im/status-go#120]
Trying to deploy a contract in Status throws the above error (when printed through a Javascript alert). Doesn't get to the point of asking for a password.

The same piece of code deploys contracts when connected to the Geth `--light` client on desktop, after the account has been unlocked in the Geth console.

There may be a valid reason for the deployment failing (not enough ETH etc.) but the generic error message makes this difficult to debug. Gas is set to 2400000.

If there's any more info I can provide please let me know.

**Comment by farazdagi** [comment]
When it comes to sending transactions (and contract creation is also done via tx sending), we updated Geth's workflow in the following way:
- request to `SendTransaction()` is intercepted, and user is blocked until one of the following happens:
  - tx timeouts
  - tx is completed (user provided password and tx can be signed using that password)
  - tx is discarded (consider it like hitting a cancel button on password screen)
- now, I am pretty sure Status node is capable of tx deployment: https://github.com/status-im/status-go/blob/master/jail/jail_test.go#L567
- @rasom can you please add more info on tx discarding, as I believe this issue is more related to the client-side (and even there it is **not** a bug, we just need to make sure that tx is completed with the correct password, rather than discarded).

**Comment by jarradh** [comment]
@morelazers  can you please provide your dapp code or a url for us to test?

**Comment by morelazers** [comment]
Sure - if you go to https://rosca-test.wetrust.io (you'll have to sign up, might have to verify email not sure) there's a small dapp there.

If you create a ROSCA, sometimes you'll get a 'Not found' error when trying to redirect, we're still looking into that, doesn't happen elsewhere. Might be related to this issue: https://github.com/ethereum/mist/issues/1560

Even if you get not found, about 50% of the time it will create a ROSCA, so if you go back to the profile it might be in the list. If it is, click it and hit deploy, you'll get a popup to warn that some users haven't joined yet. Clicking deploy again on the popup actually triggers the deployment, which throws the discarded error.

I'll speak with the team about trying to package this up as a standalone testable issue. It can be quite cumbersome testing on the phone, so I don't expect a rapid response to the issue, or one at all until we can get that standalone to you.

**Comment by morelazers** [comment]
Hey guys, quick update on this one - I just made a small test repo at https://github.com/morelazers/status-test

It is giving me the same `Transaction has been discarded` error, which is a good start.

Hopefully that helps with testing, feel free to ping me on the Status slack (@ tomnash) as I'll probably be more responsive there.

**Comment by morelazers** [comment]
Any updates on this one? I know you are massively busy preparing for the hackathon, but just thought I would ask - this is part of a use case in our hackathon dapp idea.

I got a logcat from the chat context doing the same thing here: https://pastebin.com/WKHZ9ZFp

**Comment by jarradh** [comment]
Looking into it , thanks @morelazers !

**Comment by jarradh** [comment]
@flexsurfer found the issue and we're fixing it!

**Comment by rasom** [comment]
@morelazers, problem should be fixed in `status-react`'s `develop` branch https://github.com/status-im/status-react/pull/1253
