### ISSUE TITLE
Introduce ACKs for Whisper envelopes

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-go#1278]
# Problem

One of the ways to mitigate this issue: https://github.com/status-im/status-go/issues/1276

# Implementation

A few requirements to the implementation:
1. Distinction of ACKs from a mailserver and a normal node (recipient)
1. It should not break compatibility with the current versions of status-go (e.g. old clients are ignoring these ACK messages)
1. ACKs should probably be regular whisper envelopes because it will affect darkness less

# Open questions

1. What to do with the newer client using older mailservers?

**Comment by dshulyak** [comment]
Please elaborate what do you mean by the ACK from mail server. Is that an envelope? I don't like the idea that every mail server will produce an envelope for every received message. This way volume of messages will be simply multiplied by the number of mail servers in the network.

What i wanted to introduce is a light-weight ack from a node that receives a batch of envelopes. This will be a hash of that batch, so thats 32.

**Comment by mandrigin** [comment]
Yeah, that is true, I'm not trying to force any specific implementation details.

What I want from ACKs is to be able to receive a confirmation that it reached 1 or 2 mailservers (any mailservers in the network).

Because just sending it to any peer means very little in case of heavy network partitioning and partial availability (like mobile clients). Message not leaving our node and message leaving our node to a peer that isn't connected to anyone except us is not that much different from a user perspective.

But ACK from a mailserver is more meaningful.

**Comment by dshulyak** [comment]
regarding handling confirmations that message was delivered over the network. the proposal is to extend whisper with a confirmation code. this code will be sent as a response to messagesCode. bundle that is sent as a body of messages will be hashed with keccak256 and sent as a response.

on the side of the message sender we will track sent envelopes the same way we do now, but additionally we will track the hash of the bundle. when confirmation for this bundle (hash of the bundle) will be received we will send a signal to application.

by itself this modification only provides an insurance that we will know for sure that message reached a peer. and the peer wasn't dropped after we wrote a bundle to a socket. but in order to provide a better guarantee that message reached well connected peer, we will wait for a confirmation from mail server. it means that tracker will be extended with an information about mail servers that we are currently aware of, and consider as reliable peers.

we can also provide a backward compatibility with peers that do not support confirmations. in order to do that we will send an additional flag over whisper handshake, if this flag is provided we will wait for a confirmation from a peer. if not we will fallback to a current behavior and send a signal when peer is not "flaky" and bundle was written into a socket.

@adambabik @mandrigin what are you thoughts?

**Comment by adambabik** [comment]
> it means that tracker will be extended with an information about mail servers that we are currently aware of, and consider as reliable peers.

It also means that we will keep mail servers as peers for the length of a session, right? Currently, I guess we occupy a conn slot to mail servers for a brief time when we request messages.

---

I am not really sure if there is any benefit for having this information that bundle was processed by the immediate peers. This does not provide any additional guarantees.

I like the idea with mail server confirmation. Generally, it seems like we should receive at least one confirmation: from a selected mail server or from the recipient of the message if she is online. This actually provides a strong guarantee that the message is processed by at least one party it sent to.

What is left to figure out how mail server should send this confirmation. It does not know anything about messages except for topic. Should it broadcast a confirmation for every saved message? That seems like too much overhead.

**Comment by dshulyak** [comment]
> It also means that we will keep mail servers as peers for the length of a session, right? Currently, I guess we occupy a conn slot to mail servers for a brief time when we request messages.

i thought that we are connected with mail server all the time. looking at my connection on desktop - mail server is connected all the time.

> but in order to provide a better guarantee that message reached well connected peer, we will wait for a confirmation from mail server. it means that tracker will be extended with an information about mail servers that we are currently aware of, and consider as reliable peers.

in that part i meant that we will wait for the bundle confirmation, but from mail server. only client will know the difference between regular peer or mail server, based on the configuration it has.

> I am not really sure if there is any benefit for having this information that bundle was processed by the immediate peers. This does not provide any additional guarantees.

it provides user with a feedback that envelope atleast reached the network. it kinda gives us much better guarantee than we have now. but i agree that it means nothing in highly decentralized network

> What is left to figure out how mail server should send this confirmation. It does not know anything about messages except for topic. Should it broadcast a confirmation for every saved message? That seems like too much overhead.

yep, you raised main concern. generating confirmations for every envelope will be a spam machine. especially in the network where everyone should be able to run application. we can hide this with configuration, but i don't think that this is good enough.

it is possible to imagine separate loop that broadcasts confirmations, plus signature of the mail server that this message is stored. but thats atleast hash of the envelope (32 bytes) and signature from mail server (65 bytes for secp256k1 key). but again, even if 10 mail servers generate such confirmations this is 1kb for every envelope.

do you see some other feasible way to get such confirmations? i simply don't think that it is solvable in a way we use mail servers. outlined this issue in original thread.

**Comment by adambabik** [comment]
> i thought that we are connected with mail server all the time. looking at my connection on desktop - mail server is connected all the time.

Oh maybe it has been changed again then... 

> do you see some other feasible way to get such confirmations? i simply don't think that it is solvable in a way we use mail servers. outlined this issue in original thread.

I think the same, unfortunately. Mailserver only knows of a topic of the message and that's it... Also, still if we receive a confirmation from Mailserver A and the recipient of our message uses Mailserver B, it does not mean much.

It seems like the flow needs to look like this:
1. Identity A sends a message to identity B,
2. Identity B has a mail server that it uses and it tells this mail server which topic it should send confirmations for. The confirmations are regular Whisper messages,
3. When B receives a message while being online, it can send a confirmation if it wants,
4. B's mail server always sends a confirmation if it receives a message with a particular topic.

Here, we can optimize it that an identity needs to refresh the ask for sending confirmation periodically or it needs to pay some SNT for that etc. Also, we can limit the size of bloom filter a single identity can register to send the confirmations for.

@dshulyak what do you think about this approach?

**Comment by mandrigin** [comment]
@adambabik what would it be in case of a public chat then? that is the biggest concern right now. there won't be any identity B in that case, storing the message on our own* mailserver is the best bet of ours if we don't want to hugely increase times to send messages are propagated. Then we can only ensure that the mailservers are in sync.

For someone deploying his/her own mailserver it is either a non-issue if they don't want their set of public channels to mirror ours, or they have to somehow make sure that their mailserver is in sync with our clusters and we need to provide tools for that.

*own = the mailserver that we are connected to

**Comment by mandrigin** [comment]
so, I would say, if our mailservers are in sync with each other, then having a message written to our mailserver is enough

**Comment by mandrigin** [comment]
Also, I believe we are always connected to a mailserver. We request messages all the time, whenever the app's background state has changed. If we wouldn't, minimizing the app for a few seconds and restoring it back would be enough to break the consistency of the chatroom on iOS.

**Comment by adambabik** [comment]
There is no such thing as "mail servers being in-sync". We would need to write some additional layer that would be responsible for that. That's doable it just a matter of how we want to store data, using decentralized storage like swarm or distributed database. In both cases, we need to elect a leader responsible for writes which increases centralization.

As long as all participant of a public chat use the same mail server system, we can rely on confirmation send by that system because we have a permanent connection with it, as you guys noticed :)

I think it's safe to assume that if someone uses status-* channels, they use our mail servers or their own nodes which also stores all messages. In this case, we can even simplify the flow and mail server can send confirmations directly via p2p rather than broadcasting them.

**Comment by mandrigin** [comment]
> I think it's safe to assume that if someone uses status-* channels, they use our mail servers or their own nodes which also stores all messages. In this case, we can even simplify the flow and mail server can send confirmations directly via p2p rather than broadcasting them.

yeah, and as I understand, that is exactly what @dshulyak is working on :)

**Comment by adambabik** [comment]
I think so too but I would love to see more explanation/details before we dive into coding :) I still don't feel like we have specified the solution properly. It's a huge difference whether we decide to broadcast confirmations, send them p2p or have them as a separate packet type.

**Comment by dshulyak** [comment]
> It seems like the flow needs to look like this:

this is the only flow that seems intuitively correct to me, even when network won't be controlled by us. sender has a very strict guarantee that message is either delivered to recipient's device or mail server that is reachable by recipient.

but as it was mentioned this model works well for 1 to 1, and maybe group chats. but not for public chats. it also seems to me that we cannot provide consistent UX for public chats if all participants of this chat are randomly connected to the network. some participants will not receive messages because their mail server went offline. or simply TTL of the message was too low and it didn't reach required node. some participants will receive messages much faster than other participants. maybe we should explore how we can control such consistent UX with topology, and connect public chat participants with nodes that are "responsible" for certain public chats. like in example with status-* channels.

> I think so too but I would love to see more explanation/details before we dive into coding :) I still don't feel like we have specified the solution properly. It's a huge difference whether we decide to broadcast confirmations, send them p2p or have them as a separate packet type.

probably [my message](https://github.com/status-im/status-go/issues/1278#issuecomment-439874499) was confusing. i mentioned that it will be a separate confirmation code, that is sent as a response to messages code. meaning that it is a new whisper p2p packet type.

so what kind of additional details will be useful? it is probably worth noting that our delivery feedback will depend on the fact that we control mail servers and that they are tightly connected. so if user adds one, he must ensure that this mail server is well connected to other status's mail servers.

**Comment by adambabik** [comment]
> but not for public chats. it also seems to me that we cannot provide consistent UX for public chats if all participants of this chat are randomly connected to the network. some participants will not receive messages because their mail server went offline. or simply TTL of the message was too low and it didn't reach required node. some participants will receive messages much faster than other participants. 

👍 

> maybe we should explore how we can control such consistent UX with topology, and connect public chat participants with nodes that are "responsible" for certain public chats. like in example with status-* channels.

I think it would be a safe assumption. If you want to have the best experience for `status-*` chats, use one of Status provided mail servers. But at the same time, we should make sure it works good with custom mail servers as well.

> so what kind of additional details will be useful? 

I would like to explore a few things:
* create sequence diagrams displaying how this solution will work for 1-1, group and public chats,
* what happens in a case when confirmation is not received, how long a node will wait for it?
* how does selection of mail servers happen? What if a selected mail server does go down?
* we are introducing a difference between mail servers ("our" mail servers that works best with `status-*` chats vs "custom" mail servers) -- how will that affect different participants of the network?
* if we add a new packet type, are still gonna be compliant with the Whisper spec and geth nodes?

And there might be even more questions.

**Comment by mandrigin** [comment]
> if we add a new packet type, are still gonna be compliant with the Whisper spec and geth nodes?

at least, this should be a requirement, so the old mailservers work with new clients and vice versa

**Comment by dshulyak** [comment]
> create sequence diagrams displaying how this solution will work for 1-1, group and public chats,

they all will be the same. sender receives ack from mail server. then we "hope" that message is actually delivered to the recipient, or mail server that is used by recipient. there is no confusion here, we do not provide strong guarantee. 

> what happens in a case when confirmation is not received, how long a node will wait for it?

the same as it waits now. until envelope is dropped from whisper queue. it is based on envelope TTL, which was 30s last time i checked.

> how does selection of mail servers happen? What if a selected mail server does go down?

i assume user just selects them as they do know. but we can also do several optimizations, like selecting many and ensuring that one is always connected. i created another issue to collect feedback https://github.com/status-im/status-go/issues/1285 . 

> we are introducing a difference between mail servers ("our" mail servers that works best with status-* chats vs "custom" mail servers) -- how will that affect different participants of the network?

technically the only difference would be that we manage "our" mail server, and trying to ensure high reliability and connectivity. if users are managing their mail servers the same way as we their will be very little difference.

> if we add a new packet type, are still gonna be compliant with the Whisper spec and geth nodes?

technically they will be compatible. geth nodes won't send us confirmations. i will communicate motivation for confirmations to geth devs tmrw.

@adambabik i definitely don't see this as a long term solution. it won't work if major part of network will be decentralized and not controlled by us. we need to have an application protocol that provides guaranteed delivery. but do you see other options that will provide better UX until we implement such protocol?

**Comment by mandrigin** [comment]
> they all will be the same. sender receives ack from mail server. 

actually, as a second step, we can adjust the UI on the Clojure side so we can add a timeout between a message leaving the node to a mailserver and receiving a "seen" confirmation. but that isn't a part of Whisper, it is a part of the protocol that is implemented on Clojure side.

**Comment by adambabik** [comment]
I still don't have a big picture and that's why I am asking questions :P 

I though that we actually have two cases:
1. Public chats. In this case mail servers will send confirmation using a p2p connection so a device needs a permanent connection with them but that won't clutter the network with additional messages. It requires all participants of, for example, `status-*` chats to use the same mail servers to provide some guarantees,
2. Private chat. Confirmations will be broadcasted because the sender does not know about recipient's mail server.

In case (1), if someone uses a custom mail server, they need to make sure it's in sync with Status mail servers (connecting to our nodes and making sure the mail server is available).

**Comment by dshulyak** [comment]
> Private chat. Confirmations will be broadcasted because the sender does not know about recipient's mail server

i am not sure that confirmations in private chat between peers that are not both online are useful. we will have to think about that second step more. 

> In case (1), if someone uses a custom mail server, they need to make sure it's in sync with Status mail servers (connecting to our nodes and making sure the mail server is available).

i have similar thoughts. mentioned in previous messages that custom mail server will have to be "well-connected" with our fleet of mail servers. maybe we will need to provide a user with instructions how to ensure that.

**Comment by adambabik** [comment]
> i am not sure that confirmations in private chat between peers that are not both online are useful. we will have to think about that second step more.

This is definitely something more advanced because you need additional mechanism in mail servers to tell them for which topics they should broadcast confirmations and this information needs to be persistent. I think it might be pretty cool because you at least know that recipient's mail server saved your message. However, as it's more advanced, I would be totally ok to skip this in the first iteration.

**Comment by dshulyak** [comment]
created issue in geth to collect some feedback for whisper confirmations: https://github.com/ethereum/go-ethereum/issues/18159 . we can follow up with EIP update if this use case will be relevant for whisper.
