### ISSUE TITLE
[Onboarding] Generate 5 accounts and store one with the password

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-go#1456]
**Actual behaviour**
A user enters a password -> account is generated and stored with password -> public key is sent to status-react

**Expected behaviour**
5 accounts are generated and 5 public keys sent to status-react -> user chooses one -> enters  password -> chosen account is stored with the password

**Comment by gravityblast** [comment]
It looks fine for me but I would like to review it from a security point of view (cc @corpetty).
In the current implementation the BIP44 key is encrypted and stored as soon as it's created. 
In the new implementation we need to keep it in memory until the user chooses one, or in case the user stops the onboarding and logs in with another account.
Is there any other thing we need to think about from a security point of view?

When multi-account is ready, we will have more keys to store. Shall we keep the master key in memory until the user chooses one, or only the derived keys for each account so that the master key  is not kept in memory? /cc @guylouis

**Comment by corpetty** [comment]
This pin process looks fine from a security perspective.  Me and Igor have talked about this quite a bit.  I believe ToB is going to be spending some time ont he app itself in the near future as they've brought a few on and they've started asking about building and finding binaries. 

About storage of keys for multiaccount.  I propose we never store the master key in memory, and only keep it's subkeys that are being used in memory for only the time they are needed.  as per the diagram [in miro](https://miro.com/app/board/o9J_kxw_3_4=/).   If something needs to be stored, it should be encrypted and stored in whatever secure hardware is available on the device using the same process listed above. 

The goal is to ensure that if one of the specific master keys gets compromised, it doesn't compromise the security of the others.  If we store the main master key, that will always be the case.

**Comment by gravityblast** [comment]
can we split this in 2 tasks one for the generation of 5 accounts to keep in memory until the users chooses one, and one task for the PIN usage? 
If I understood correctly once we switch to use a PIN we must change the way we store keys, so hey can be managed as 2 different things.

/cc @guylouis @rachelhamlin @corpetty @flexsurfer @mandrigin

**Comment by flexsurfer** [comment]
i've created a new issue for a pincode https://github.com/status-im/status-go/issues/1463

**Comment by gravityblast** [comment]
@flexsurfer I opened a PR https://github.com/status-im/status-go/pull/1464
We can start using the artifacts to test it
