### ISSUE TITLE
Multiaccounts: wallet_checkDerivationPaths method

### ISSUE THREAD

**Issue by yenda** [status-im/status-go#1507]
# Problem

When importing an account in the multi account wallet from a seed phrase, the app needs to show the user paths that are already used an contain funds

# Implementation

We would need a function that given a seed phrase, returns as efficiently as possible the balance of assets if there is any for all known derivation path, potentially we could call it like this:
`wallet_checkDerivationPaths(seedPhrase, ERC20Contracts, derivationPaths)`

and it would return map with derivation paths as keys and maps of contractAddress and balance as values

**Comment by dshulyak** [comment]
the derivation is slightly separated from wallet service, maybe, @gravityblast do you have a public method that i can use to get list of accounts (public keys or addresses) based on seed phrase and derivation paths?

**Comment by gravityblast** [comment]
@dshulyak maybe we can do the opposite. From the StatusAccounts servic I already have a mapping of derivationPath =>  address, I can call something passing a list of addresses and get back balances.
Would it make sense? 
That's because the key is in memory and we don't want to expose it anywhere. 
But it's not the "saved" key. It's a temporary one that we have in memory to decide which account to save based on the balance

**Comment by gravityblast** [comment]
or actually, the StatusAccount service already returns a list of map => addresses to react. and then react can query the wallet service with each address to get the balance. what do you think @dshulyak @yenda ?

**Comment by yenda** [comment]
yes so I would only pass a list of addresses and the list of token contract addresses to the function then
