### ISSUE TITLE
Store sub accounts information in status-go

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#1552]
# Problem
With multiaccoutns functionality user can derive mutliple keys to use with the status account.
Types:

* main (when it is used?)
* wallet (used for signing transactions)
* watch (transactions history will be watched for this type)
* another type?

Main and wallet accounts should be unique, e.g. you can't choose another main without disabling previously selected.

This information will be used when user logs in to fetch required sub accounts from database and pass them to components that needs them. For instance, wallet address will be passed to accounts manager, and watch address will be passed to transfers watcher.

# Implementation
We will add one table that will store list of addresses with types that are specified above.
And api with following methods:

## accounts_saveSubAccounts
Accepts list of accounts, e.g.

```json
[
{
"address": "0x0100000000000000000000000000000000000000",
"main": true,
"wallet": true,
"watch": false
},
{
"address": "0x0200000000000000000000000000000000000000",
"main": false,
"wallet": false,
"watch": true
}
]

```

Preserves constrains specified above.

## accounts_getSubAccounts
returns all accounts in the format above.

# Acceptance Criteria
Account list stored in status-go, used during login and can be modified.

@flexsurfer @yenda take a look please, especially i need to clarify types and api

**Comment by yenda** [comment]
I am not sure main is needed but chat is needed imo as an account whose key is loaded in memory when starting the node

**Comment by flexsurfer** [comment]
i'm not sure i understand this one,
so we have multiaccount - it has a root address, we'll derive all addresses from this one, also we have two default accounts, 1 - for chat , 1 - for wallet (i'm not sure why we call it main account)
for login we'll need root adress and chat account, because we need to show username and public key of chat account, and i'm not sure why we also need default wallet (main account) in login method `status/login address password main-account watch-addresses`

account fields
public key?
default?
address 
type (:derived, :imported, :watch-only)
path (E.g. default account “m/44’/60’/0’/0/0”)
storage (:device, :keycard)
name
color

**Comment by yenda** [comment]
@flexsurfer for login you just need what you have to display + unique identifier so it can be as little as name + chat account public key because the chat account public key is unique to each account and last log in timestamp. Such a table already exists.
This issue is after login, it's a table encrypted per multiaccount. So from what you wrote I suppose we should separate fields that are for status-react and fields that are for status-go.
For status-go I think the important fields are:
- address
- has-private-key? (false would be watch-only)
- load-private-key? (true would be chat account, the account is loaded at login)

Are we storing the root account somewhere when the user doesn't have a keycard?

For status-react the following fields are also needed:
- public-key (I suppose only true for chat account?)
- default? 
- type path and storage might need more thinking are we showing those in the UI? Are they necessary?
- name and color

**Comment by flexsurfer** [comment]
> type path and storage might need more thinking are we showing those in the UI?

yes

**Comment by yenda** [comment]
also it seems @dshulyak prefers booleans over enumerations, is it for indexing purposes? We could use enumerations or even strings for react only fields and stick to booleans for things used by status-go

**Comment by dshulyak** [comment]
> public key?

do we show public key only for chat account  and for all other accounts we show only address?
status-go doesn't need this information, i will add blob for any binary data, it will be returned in a hex to caller

> default?

we can have defaults for wallet and for chat? and potentially for other functions as well (like browser)? or what it means?

> type (:derived, :imported, :watch-only)

can we disable watching an account or it is not necessary?

**Comment by dshulyak** [comment]
> also it seems @dshulyak prefers booleans over enumerations, is it for indexing purposes? We could use enumerations or even strings for react only fields and stick to booleans for things used by status-go

i used boolean because then i can set same account to be default for wallet and chat functions and enforce this constraint on a db level. for other cases i can use enumeration

**Comment by flexsurfer** [comment]
> do we show public key only for chat account and for all other accounts we show only address?

yes, chat account is different maybe better to store chat public key and name in multiaccount object and do not have a separate account for it

> we can have defaults for wallet and for chat? 

see above, i'm not sure we'll have several chat accounts in near future

> can we disable watching an account or it is not necessary?

we can't disable, only remove account, fields you can edit are name and colour

**Comment by flexsurfer** [comment]
so my suggestion is
multiaccount
-address (root)
-publickey (chat) - derived from root address
-name (generated from chat public key or ens name) - can be changed

account
-root-address (connection with multiaccount table)
-address  (react-native) 
-default? (react-native) - can be changed
-type (:derived, :imported, :watch-only)  (react-native) 
-path (E.g. default account “m/44’/60’/0’/0/0”)  (react-native) 
-storage (:device, :keycard)  (react-native) 
-name (react-native) - can be changed
-color (react-native) - can be changed

**Comment by yenda** [comment]
> > do we show public key only for chat account and for all other accounts we show only address?
> 
> yes, chat account is different maybe better to store chat public key and name in multiaccount object and do not have a separate account for it
> 
If you mean in the db that lists all multiaccount that is a no no we should really keep the amount of information in this db to a minimum. Also there is no difference between a wallet and chat account except that the chat account is loaded in memory at login and the wallet address is watched by the wallet module

> > we can have defaults for wallet and for chat? 
> 
> see above, i'm not sure we'll have several chat accounts in near future
> 

Maybe not in the near future but we will. But does status-go needs to know about default? It might probably just be a status-react thing, the account to use being passed with the post call for whisper or sign transaction call for wallet.

> so my suggestion is
> multiaccount
> -address (root)
> -publickey (chat) - derived from root address
> -name (generated from chat public key or ens name) - can be changed

Looks good to me, there is also login timestamp
chat account is derived from root account not root address but that's a detail.
For now I'm ok with these fields, but we should discuss with UX, personally I think that we shouldn't show any address/pk in the login listing, maybe just an identicon based on root address for the user to recognize his address, or nothing since the name is likely to be unique per account on device

> 
> account
> -address (react-native)
> -default? (react-native) - can be changed
> -type (:derived, :imported, :watch-only) (react-native)
> -path (E.g. default account “m/44’/60’/0’/0/0”) (react-native)
> -storage (:device, :keycard) (react-native)
> -name (react-native) - can be changed
> -color (react-native) - can be changed

I think @dshulyak wants to use a json blob for all the react only fields

**Comment by dshulyak** [comment]
> yes, chat account is different maybe better to store chat public key and name in multiaccount object and do not have a separate account for it

for consistency i like all accounts to be stored in one place if that preserves all functionality. and it seems to me that it does. so i will keep chat account in accounts table and add public key field to that table.

This is what i have:

```go
type Account struct {
	Address   common.Address `json:"address"`
	Wallet    bool           `json:"wallet"`
	Chat      bool           `json:"chat"`
	Type      string         `json:"type"`
	Storage   string         `json:"storage"`
	Path      string         `json:"path"`
	PublicKey hexutil.Bytes  `json:"publicKey"`

	Name  string `json:"name"`
	Color string `json:"color"`
}
```

> -root-address (connection with multiaccount table)

in status-go this field is unnecessary because we have a separate db for every multiaccount encrypted with its password, hence there is no multiaccount table

**Comment by flexsurfer** [comment]
@dmitryn hm but you need chat account before login, if it will be encrypted with password you can't get it, also chat account doesn't have all these fields only two

**Comment by yenda** [comment]
@flexsurfer technically the chat account is "derived", has a "path" (@gravityblast  which one?), is stored on device, and the only thing that differentiates it from a wallet account is that it is not monitored by the wallet service and that it's key is loaded in memory after login so that it can decrypt incoming message. And unless we put some limitations in place, I think a user could even manage to import his chat account as a wallet

**Comment by flexsurfer** [comment]
> has a "path" ( which one?)

"m/43'/60'/1581'/0'/0"
