### ISSUE TITLE
do not return private key in the result for VerifyAccountPassword

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-go#1882]
do not return private key in the result for VerifyAccountPassword

**Comment by 0kok0** [comment]
can you provide more context @flexsurfer

**Comment by flexsurfer** [comment]
we want to use VerifyAccountPassword in status-react, but we just want to verify password, we don't need private key, currently VerifyAccountPassword returns two arguments json  and private key, so we need only first one in status-react

**Comment by 0kok0** [comment]
I guess we need the private key _only_ in GethStatusBackend to sign, otherwise it's only used as you describe to verify the password.
I'd go for a bool determining if the privkey is returned and multiple returns here, as if we split it in two functions there's more exposure and surface to be maintained for private key handling. 
What do you think?

**Comment by flexsurfer** [comment]
I'm not familiar with go code, so I'm ok with any solution ;) bool is fine for me, thanks

**Comment by flexsurfer** [comment]
sorry for the confusion, there is no private key in results
