### ISSUE TITLE
Send result miss returned value when multiple transactions are pending

### ISSUE THREAD

**Issue by jeluard** [status-im/status-go#192]
When a transaction is sent (but unsigned) then discarded `send` command unblocks with payload:

```clojure
{:result {:context {}, :messages [], 
:returned {:error 
    "Invalid JSON RPC response: {\"error\":{\"code\":-32603, 
    \"transaction has been discarded\":\"transaction has been discarded\"},
    \"id\":20,\"jsonrpc\":\"2.0\"}"}}}
```

If multiple transactions are pending (i.e. unsigned) and one is discarded associated `send` unblocks with:

 ```clojure
{:result {:context {}, :messages []}}
```

I would expect both answers to contain the `returned` field.

**Comment by tiabc** [comment]
What's the expected behavior for signals? Please, correct me where I'm wrong.

For `SendTransaction(...)`: hang on until the transaction is processed and always return its `id`, `hash` and `error` indexed by its id.

For `DiscardTransactions(id)`: once the tx has been discarded, immediately return the very same data structure with `error: "transaction has been discarded"`.

What branch are you using?

**Comment by rasom** [comment]
@tiabc as far as I know we don't have any problems with signals atm. The problem is that if we are making two RPC `eth_sendTransaction` calls (from jail) and both stay pending. When we discard one of them we don't receive proper response from RPC call with, it doesn't contain `error`.

I will double-check what exactly response we receive.

**Comment by jeluard** [comment]
@tiabc this is with `status-react` develop.

Exactly what @rasom said. `DiscardTransactions` is fine.
`status-react` side we don't get the `returned` part when multiple transactions are in flight (not sure how `returned` is mapped from the go answer).

**Comment by tiabc** [comment]
Thanks. Let's get back to this issue when we finish #190.

**Comment by MarinX** [comment]
The problem is in the second transaction sending - takes more time then sending first transaction.
I tested it on go side and there was no problem, RPC is returning error message that transaction has been discarded.

However, sending second transaction and calling `DiscardTransactions` with empty string returns no response -> issue here.

Please test on `status-react` side and see if you have transaction id before doing `DiscardTransactions` of transaction.

Also, maybe we should implement an error if transaction ID is empty string on `status-go` side ?

**Comment by tiabc** [comment]
@roma, can you test it on your side, please?
@MarinX, yes, let's do it. Probably, we should check if the transaction id is empty at the moment internally during processing and not in our Facade (signals).

**Comment by jeluard** [comment]
I will look at it later today. If you can add some more error checking that would be great, yes!

**Comment by MarinX** [comment]
Added more tests.
Seems like error is ok handled from DiscardTransaction.
Here is the log on `status-go` side sending 2 transactions and discarding 1.
I tried sending >2 transactions, and discarding the first, the last, the middle and every call was success.
So, I cannot reproduce the bug on `status-go` side.

[gist log](https://gist.github.com/MarinX/20c6e778258ec7c1b4dbeabb3dffbc1b)

**Comment by jeluard** [comment]
Can you do the following test: send 2 transactions, discard the first sent.

I can see differences in behavior depending on which transaction gets discarded first but not quite sure yet if this is go side or not.

**Comment by MarinX** [comment]
Its same.
I tried multiple variations to reproduce, same thing.
I always receive RPC response on go side.

Here is the gist log for discarding first transaction
[gist2.log](https://gist.github.com/MarinX/eba0f6f908d1dd952f6146ae82942123).

Btw..which node network are you using ? (Ropsten / Rinkeby). I doubt it is a node network issue, but again, we can try it.

**Comment by adambabik** [comment]
I tried to reproduce this bug and there is something wrong with discarding transactions, but it's a bit different. I used status-go (https://github.com/status-im/status-go/commit/8fb2424ea564beddf42b522066c52ca670ec82a9) and status-react `feature/upgrade-status-go-g0270590`.

### Scenario

1. Create a transaction for user A, but don't confirm it,
2. Create another transaction for user B, but don't confirm it,
3. Open a list of unsigned transaction from the left pane,
4. Discard the transaction with user A -- **error** -- the transaction with user B disappears,
5. Close the left pane and open it again -- it has the proper state, only the transaction with B is visible,
6. Discard the transaction with user B -- worked successfully, all transactions are gone.

One more bug I discovered is that when you create a transaction with one user, close it without confirming and try to create another transaction with the same user, it won't allow you. The send button and input field are not responsive, fee does not load, but there is no error or warning screen.

**Comment by tiabc** [comment]
@jeluard is this still relevant?

**Comment by jeluard** [comment]
This was with the old wallet so this exact scenario does not exist anymore. Will reopen if it still applies with new wallet.
