### ISSUE TITLE
MultiAccountStoreDerived reports account already exists while RPC API doesn't

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-go#1939]
# Problem

The original problem was reported at https://github.com/status-im/status-react/issues/10326 but it seems to boil down to misbehaviour in `status-go`.

As described in this https://github.com/status-im/status-react/issues/10326#issuecomment-615146351 adding multiaccounts (watch only) and removing them again, seems to not properly remove them from status-go cache.

While the RPC API `accounts_getAccount` properly returns the latest state with only the main multiaccount and the chat account being available, `MultiAccountStoreDerived` still emits an error that the account in question `'already exists'`.

I **assume** https://github.com/status-im/status-go/issues/1896 and https://github.com/status-im/go-ethereum/pull/87 are related to this.

Happy to help debugging/verifying this on status-go' side. Any pointers to make that happen are highly appreciated :)

# Implementation

Need to verify if this is really the case or of there's something else off. Skimming through the code it looks like status-go is returning accounts from cache, so there might be an issue with accounts not being properly removed from cache.

As a matter of fact, while adding a new multi account calls into native status-go inside status-react here:
https://github.com/status-im/status-react/blob/a79a72fccb27911b0caf96534a52215ba162d92b/src/status_im/native_module/core.cljs#L133-L137

and therefore here:

https://github.com/status-im/status-react/blob/a79a72fccb27911b0caf96534a52215ba162d92b/modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java#L744-L760

It doesn't look like the same is happening with the account deletion:

https://github.com/status-im/status-react/blob/a79a72fccb27911b0caf96534a52215ba162d92b/src/status_im/wallet/accounts/core.cljs#L252-L265

Instead it's going through the RPC API. Maybe that is bypassing the cache?

Just thinking out loud here, hope this is useful information.

**Comment by flexsurfer** [comment]
@gravityblast could you take a look?

**Comment by gravityblast** [comment]
> As described in this status-im/status-react#10326 (comment) adding multiaccounts (watch only) and removing them again, seems to not properly remove them from status-go cache.

hey @PascalPrecht , I'm happy to help! 
How do we remove accounts?
In the current implementation, the Multiaccount functions use the [account/generator](https://github.com/status-im/status-go/blob/develop/account/generator/generator.go) package to generate, derive, and store keys in keystore json files. 
I don't think we have implemented something to remove those accounts physically from the filesystem.
Where and how do we store watch-only accounts?

**Comment by gravityblast** [comment]
@PascalPrecht @flexsurfer 
as specified in point 3 of the issue https://github.com/status-im/status-react/issues/10326, the problem occurs when the account is added as a normal account as well. 
It makes sense because the "remove watch-only" action doesn't remove the keystore file.

**Comment by gravityblast** [comment]
maybe for now we can avoid adding a normal account that is already in the watch-only list?

**Comment by flexsurfer** [comment]
yes we do that, we don't add account if its in watch -only,  also there are not keys for watch-only dunno why there is an error

**Comment by gravityblast** [comment]
This issue https://github.com/status-im/status-react/issues/10326 says
> BIG HINT: It's all fine if you do not add the same account while Watch only address (so if you repeat Reproduction but without 3rd step then all fine)

It looks like adding a normal account that is already a watch-only one actually changes something. I expect go is not even called in that case right?

**Comment by gravityblast** [comment]
as @PascalPrecht said maybe when we add watch-only accounts, they are added in the keystore cache? what do we call in Go when we add a watch-only account?

**Comment by flexsurfer** [comment]
`json-rpc/call [{:method     "accounts_saveAccounts"`

**Comment by 0x-r4bbit** [comment]
@gravityblast Thanks for getting back to me on this. 

So yes, removing accounts isn't actually an option for non-watch-only accounts. Anything I can do to help here?

**Comment by gravityblast** [comment]
I tried debugging with a custom build of `status-go` and here what I see:

1 - create a new multi-account
2 - import `0xB7` as watch-only address (the account/generator pkg in go is not called, which is ok because it's only added to the db, no keystore file)
2 - I import the mnemonic that generates the same address and the UI shows `account already exists` (we said it shouldn't call the account/generator, but actually it calls its method StoreDerivedAccount, which check that the account doesn't exists on the filesystem, and it creates it successfully returning no errors)

@flexsurfer is it possible we check somewhere else if the account already exist? cause that specific call doesn't return an error

**Comment by gravityblast** [comment]
I tried debugging with a custom build of `status-go` and here what I see:

1 - create a new multi-account
2 - import `0xB7` as watch-only address (the account/generator pkg in go is not called, which is ok because it's only added to the db, no keystore file)
2 - I import the mnemonic that generates the same address and the UI shows `account already exists` (we said it shouldn't call the account/generator, but actually it calls its method StoreDerivedAccount, which check that the account doesn't exists on the filesystem, and it creates it successfully returning no errors)

@flexsurfer is it possible we check somewhere else if the account already exist? cause that specific call doesn't return an error

**Comment by andremedeiros** [comment]
Correct me if I'm wrong, but it sounds to me that the issue lies with the way the keystore json files are stored, no?

**Comment by gravityblast** [comment]
@andremedeiros it shouldn't be an issue with that.
normal account private keys are stored in keystore files in the filesystem. then in the db we store the addresses of the accounts.

with watch-only accounts we store only the address in the db.

inside a multiaccount a user can import a mnemonic, but we should call the multiaccount-api to store the new account in the filesystem only if it's not already present as a watch-only account in the db.

In this case I see that the multiaccount api is called anyway, and it successfully saves the new account because it's not yet in the filesystem.

the only thing I don't understand is why the UI shows "account already exists" even if `StoreDerived` doesn't  return an error. maybe we call another api after that?

**Comment by flexsurfer** [comment]
@gravityblast yeah after account generated we have this check https://github.com/status-im/status-react/blob/cc70a7e8dab06a614a4f010b404105e218a1b413/src/status_im/wallet/accounts/core.cljs#L192

**Comment by flexsurfer** [comment]
so we shouldn't allow storing account if it exists in status-react

**Comment by gravityblast** [comment]
yeah I think the final fix would be for status-react to validate the
uniqueness of an address before generating and storing the key in the
filesystem.
