### ISSUE TITLE
slow CreateAccount method

### ISSUE THREAD

**Issue by rasom** [status-im/status-go#251]
`CreateAccount` started to be slow in [`develop`](https://github.com/status-im/status-go/commit/02705906469a1a44e6ea89e51eb71628045b0b5f), it takes 20-45 seconds before callback is invoked on real device (iphone 6s).

Previously it worked much faster, 1.5-2.0 seconds in `bug/whisper-on-geth1.6.1`.

**Comment by tiabc** [comment]
@rasom:
> i would treat this issue as a high priority because we can’t add such regression to the next release, that means that we will not be able to upgrade status-go in the app and use any new features (JSON RPC, PN stuff, whatever). Just my opinion

**Comment by MarinX** [comment]
I did a test to call CreateAccount and it does not takes that much.
Log output:
```
	utils.go:1450: {"type":"node.started","event":{}}
	utils.go:1464: Node started, but we wait till it be ready
	utils.go:1450: {"type":"node.ready","event":{}}
	utils.go:123: === RUN   test create account
	utils.go:1428: Account created:  {"address":"f4a41a7cfd72e2b3da0f07f4f534b2c969ebe3d0","pubkey":"0x042d7e2edfaa4aa1ee4241c9e0e401315f7cbd66ff4d98a4a279cc95df1e7ad744103bdfeeb0a5b1cbe8c60894c0525103ab1005f58c24e4915e66a2ecd8bb8a01","mnemonic":"fault whale tooth hollow chat vibrant ten stem hospital birth fish expose","error":""}
	utils.go:1429: Time elapsed 0.266428395  seconds
```
**Time elapsed 0.266428395  seconds** - which is not a full second.
Please check the `status-react` code and try to do timing on functions.

**Comment by rasom** [comment]
The difference is noticeable only on real mobile device.

**Comment by tiabc** [comment]
Please, start doing #257 under this issue. No need for signals now, just a separate profiling service which automatically starts when CreateAccount is invoked and stops when it finishes.
The path for storing the profile file is worth discussing with @rasom. And after @rasom runs the code, you'll have all the data to dig in and spot the issue without unneeded back-and-forth.

**Comment by jarradh** [comment]
Can we please confirm this is using LightScryptN and LightScryptP, if it's taking longer on mobile device but not on desktop it's probably using StandardScryptN and StandardScryptP

**Comment by MarinX** [comment]
I can confirm that we are using `LightScrypt`. 
From go-ethereum node config there is an param `UseLightweightKDF` [here](https://github.com/status-im/status-go/blob/278b231efad38927396829e619e4965c5523a0f2/vendor/github.com/ethereum/go-ethereum/node/config.go#L356) to use `LightScrypt`. We are sending it [here](https://github.com/status-im/status-go/blob/278b231efad38927396829e619e4965c5523a0f2/geth/node/node.go#L93) as `true`, so its enabled.

**Comment by tiabc** [comment]
@rasom:
> yes, that’s it, previous commit (`06758cdb7f7b5240f78aeaa144c6e14b8cffff19`) is fine, this one `4d4c3ea4aabeb98e00644c197fd094fc69996b88` is slow

**Comment by divan** [comment]
I can confirm that issue appeared in the above-mentioned commit (https://github.com/status-im/status-go/pull/189). On an Android Emulator the difference in CreateAccount between 06758cdb7f7b5240f78aeaa144c6e14b8cffff19 and 4d4c3ea4aabeb98e00644c197fd094fc69996b88 is 3-7s vs 20-29s.

Adding profiling didn't work for me (the app crashes with no output on `SetCPUProfile()` in emulator), so I did manual profiling using logging. The culprit function was easy to spot - it's https://github.com/status-im/status-go/blob/4d4c3ea4aabeb98e00644c197fd094fc69996b88/vendor/golang.org/x/crypto/scrypt/scrypt.go#L175.

It get's executed three times during CreateAccount and takes more than 70% of the total CreateAccount execution time (~21s out of 29s). These numbers are consistent between many attempts. In contrast, before that commit, it took less than 200ms with total execution time around 3s.

Looking at the commit that introduced the issue, there is no obvious explanation for this slowdown in a crypto code (which haven't change for a year). The problem seems to be more subtle and more investigation needed.

**Comment by divan** [comment]
After analysis of original commit and debugging code introduced, the problem seems to be in this loop: https://github.com/status-im/status-go/blob/develop/vendor/fknsrs.biz/p/ottoext/loop/loop.go#L172
```go
outer:
	for {
		select {
		case t := <-l.ready:
			if t != nil {
				if err := l.processTask(t); err != nil {
					return err
				}
			}
		default:
			break outer
		}
	}
```

The same instance of `Loop` is being run multiple times. In the first run it executes and `close(l.ready)` closes the channel.
On subsequent run, it goes into the `outer` loop and `<-l.ready` always returns nil, as channel already closed. And the loop repeats infinitely, the call never ends and, supposedly, uses a lot of CPU - at least enough to make things slow.

So, it's not only CreateAccount slow, it should slow other things. I have no idea how device handles such cpu-expensive loops, but UI seems to be not affected to much. The difference becomes evident in CPU heavy tasks as crypto, hence visible slowdown of CreateAccount.

This also explains, why bug is not reproduced locally, but only on device/emulator.

Next patch seems to solve the issue, but I'm not sure yet how it supposed to work originally. Maybe the design of the `loop` package is completely wrong (@influx6 suggested that it begs for refactoring in any case).

Anyhow, this fix solved problem in emulator, confirming the guess:
```diff
diff --git a/vendor/fknsrs.biz/p/ottoext/loop/loop.go b/vendor/fknsrs.biz/p/ottoext/loop/loop.go
index ac97dc5..6c319e9 100644
--- a/vendor/fknsrs.biz/p/ottoext/loop/loop.go
+++ b/vendor/fknsrs.biz/p/ottoext/loop/loop.go
@@ -172,7 +172,10 @@ func (l *Loop) Run() error {
 outer:
 	for {
 		select {
-		case t := <-l.ready:
+		case t, ok := <-l.ready:
+			if !ok {
+				return nil
+			}
 			if t != nil {
 				if err := l.processTask(t); err != nil {
 					return err

```

**Comment by tiabc** [comment]
Thanks, Ivan. I'll check your fix later today.

**Comment by tiabc** [comment]
So yeah, the same loop should never be run several times. The current behaviour is happening due to #260 with the easiest fix to destroy all existing jail cells upon account switching. @influx6 has been right about this.
@divan please, tackle #260. I believe it can be finished really fast.

**Comment by tiabc** [comment]
@annadanchenko @rasom please, verify.
