### ISSUE TITLE
Two accounts on the same device can't communicate to one another

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#252]
See https://github.com/status-im/status-react/issues/1391 for details.

**Comment by rgeraldes** [comment]
Whisper, caches the envelope when he publishes the message in the network it in order to ignore duplicate envelopes in the future.
This means that if we have two accounts one the same mobile phone, **we are using the same whisper node** which will publish the message, so we will not be able to receive it in a different account.

**Comment by influx6** [comment]
Whats the current plan as regards this issue, I would take it but am not fully understand what is meant to be done. if according to @rgeraldes, if it's a protocol issue then does that mean `go-ethereum` and if not, how are two accounts on the same device are expected to communicate. 

When say communicate, do we mean:

- Send chat messages between the two
- Send ether between accounts.

In my mind, I see this as an issue of session details, if we can provide distinct session data related to both accounts and ensure to reach out to those sessions for example `using the password associtated with that account to complete transactions`, would this resolve this issue?

**Comment by adambabik** [comment]
If someone changes an account, don't the app stops and starts the node again? What does determine if it's the same or a different node?

**Comment by rgeraldes** [comment]
In detail:
https://github.com/status-im/status-go/blob/develop/vendor/github.com/ethereum/go-ethereum/whisper/whisperv5/whisper.go#L706

Envelope is cached when it's published. Since it's already cached it will not post the event to the watchers.

**Comment by influx6** [comment]
After much look into goethereum and status-go side of things, am concluding we can not reproduce this behaviour or simulate it on the go side has describe due to specific architecture of ethereum and whispers approach of sending messages.

Generally to deliver messages over whisper which is what is done in between accounts whether on same device or different device, the following is done:

1. Each accounts Private and associated public keys are loaded into whisper either through the `whisper.WhisperService` or `whisper.WhisperAPI`.
2. Each accounts public key is turned into hex format after unwrapping with `crypto.FromECDSAPub` to get string version of Public key.
3. Message is assigned necessary signature `sig` and public key id `pubKey` to used and sent over `whisper.post` or `ssh_post` rpc method.
4. Whisper stores message into cache till its expiration of `TTL` value before removal and notifies all filters if present of new message.
5. A filter with associated accounts can be created, where accounts keys are used has signature `sig` and private key `privateKeyID` (representing the receivers key). Which we can then pull messages for that filter using `ssh_getFilterMessages` or `whisperServices.Messages`.
6. Poll filter if on the client side for new messages if needed.

In all, we have no such concept has logging in and out of accounts, infact `AccountManager.SelectAccount` only sets a giving account key has active within the whisper service but does not in anyway affect delivery of messages or it's transmission.

Its up to the user either on the go side or on the client to create necessary filter for that specific message through its topic with associated signature and privateKeyID, that is pretty much the only way a message is retrieved.

Hence, in my view, the real problem here is the user not receiving a notification of a message. 

Being that the case, we would need to ensure or atleast hook into when `AccountManager.SelectAccount` is used which we consider a logging, to seek notifications for cached messages to be delivered to account, but this can create a few problems.

1. We must have a list of messages already notified to user and that user has seen
2. Diff out the new messages that have arrived and notify user when logged in, am not sure if the JSON RPC API method `shh_getFilterChanges` (see https://github.com/ethereum/wiki/wiki/JSON-RPC#shh_getfilterchanges) might help in this instance.
3. Ensure we are not notifying multiples times because of cached messages.

**Comment by influx6** [comment]
@tiabc Any update on this?
