### ISSUE TITLE
All commands should be properly routed to the local node or the specified upstream

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#274]
Infura does not support Whisper.

@rasom 
> https://github.com/status-im/status-go/issues/190#issuecomment-312764957 see 4. in this comment

This means that all `shh_*` commands should not be forwarded to the upstream RPC client.

@influx6 
> Ya, they are going to upstream currently due to this: https://github.com/status-im/status-go/blob/develop/geth/jail/execution_policy.go#L148

> The NodeManager.RPCClient will return an appropriate `rpc.Client` for upstream.
https://github.com/status-im/status-go/blob/develop/geth/node/manager.go#L506-L551

> Aside from that, we can add another exception to https://github.com/status-im/status-go/blob/develop/geth/jail/jail.go#L207-L212

There was an idea to solve it with two new methods: `NodeManager.RPCLocalClient()` and `NodeManager.RPCUpstreamClient()`.

**Comment by tiabc** [comment]
These calls weren't even supposed to be forwarded to an upstream node, this requirement just got lost among other questions. So there's no point in relaying whisper calls to an upstream just because we must run whisper in order to receive messages. And if we run whisper, we can send messages using it.

This issue should be more systematic and be renamed to "Figure out the rules of routing geth commands". The rules are the following:
1. All request regarding current blockchain state should be forwarded for the upstream node.
2. Other commands: whisper commands, geth client version, accounts and unknown requests should be executed locally.

I'd like to see a wiki page describing which queries go where from the implementor just before writing any code. This page would be useful for everyone from the other team as well as any person familiarising with the code.

**Comment by influx6** [comment]
@tiabc so as I understand this, we need to write a doc in the wiki for the project detailing the different JSON RPC commands and where they go in the two category:

- Upstream
- Local

Futhermore, we should also break these commands down into the following sets:

- Blockchain state requests 
- Whisper commands
- Geth commands
- Account Commands
- ...etc

Before we continue any implementation work for this issue, correct?

**Comment by tiabc** [comment]
Not exactly. Also, don't take this too seriously, this doc may be finished in half an hour in a table of 3 columns (command, destination, comment). You can use any format: either google doc, or wiki, whichever is faster for you.

Just take the list from https://github.com/ethereum/wiki/wiki/JSON-RPC and assign whatever destination each command deserves and write a comment why. That's it. You can put it here for review and tackle the issue without waiting for the response.

**Comment by influx6** [comment]
Alright, understood.

**Comment by influx6** [comment]
@adambabik @rasom  @tiabc Included within the google doc spreadsheet is a initial breakdown of rpc commands and what i believe the current area it should be process to be.

https://docs.google.com/spreadsheets/d/1N1nuzVN5tXoDmzkBLeC9_mwIlVH8DGF7YD2XwxA8BAE/edit?usp=sharing

Please review. Also, we should move it into status own account.

**Comment by tiabc** [comment]
@adambabik please, be first to review the list of commands.
@influx6 you can create a document from your status.im account and share with the company next time. But don't bother for now, this will eventually go into wiki anyway.

**Comment by adambabik** [comment]
I found just one thing - `eth_accounts` - which I guess should be handled with the local node. Others look good to me (bear in mind that my Eth knowledge has still some gaps :P).

**Comment by tiabc** [comment]
@adambabik this is why I've asked you to review first - to become more familiar with Ethereum JSON-RPC API.
@influx6 thanks, fixed possible wrong places. Please, proceed with the implementation. I'd currently stick to whatever we already have even if its architecture is not great just to finish it today. All that architecture about a delegate json rpc server deserves a thorough look and refactoring so let's not bother about it now.

**Comment by tiabc** [comment]
Thanks, that was good one!
