### ISSUE TITLE
Refactoring: improve error handling

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#287]
Currently, errors are just passed to the caller which is not great for problem solving. Let's utilise github.com/pkg/errors and wrap errors with context, not just pass them without handling.

**Comment by themue** [comment]
Yes, definitely. Doing the same in my own code with my according Tideland `errors` package leading to more useful nested errors.

**Comment by divan** [comment]
@tiabc are you referring here to specific package or the whole status-go project?

I think we're currently using quite diverse cases of errors. "Passing to the caller" techically also counts as "handling errors - sometimes it's just right thing to do, and we always can enrich error with `fmt.Errorf()` - a bit limited, but default option.

For example, in `jail` packages there are 36 checks for errors and only 14 pass error to the caller. (calculated with `rg "if err" geth/jail/ | wc -l` and `rg -A 3  "if err" geth/jail/ | rg "return err" | wc -l` commands).

`github.com/pkg/errors` is nice, but it can be easily misused as a "new default option to handle errors". In reality we rarely need stacktraces and it's trivial to add them in (our) code when we need them.

Generally, there are two approaches:
 - wrap errors with metainformation/stacktrace and return to the upper caller, where error will be properly logged/processed
 - decide locally what need to be done in this particular error case - ignore, silently pass to the caller, enrich with context info, add stacktrace, print log message, try another call, etc, etc.

First method is good when program structure is purely hierarchical and uniform. Second is more flexible, but requires more attention from developers.

I stand for the second one. And here are two notes on logging and stacktraces.

## Logging
Whenever possible, log short and precise human-readable error message as low the stack as possible. Pros:
 -  allows to have actual file:number information (which is often more than enough to understand where error is happened)
 - can be tested (if tests initialized with log mock, buffer variable for writer, etc), it's possible to test that logs are correct for error paths
 - simple and clean, code locality is better (easy to understand what will be logged just by looking at error handling code)
Cons:
 - can add log dependency for small packages (in this case, though, we might move logging to the caller)
 - more attention needed for each error case

## Stacktraces
They're great when the program is huge, understanding of the codebase is limited and design is complicated, so many function can have multiple possible callers. For simpler programs and cleaner designs, it's almost always enough to have file and line number information to understand where error is happened.
Stacktraces embodied into errors variables also can be huge and have some unjustified performance hit, so they can be used only where it's justified.

Some similar previous discussions here:
https://github.com/status-im/status-go/issues/295#issuecomment-327038700

**Comment by screwyprof** [comment]
The suggested package is not a panacea. It is really great and all that, but it can be overkill or even unnecessary evil in some cases.

The questing is what problem are we exactly going to solve? Just adding some context to errors? It can be done without wrapping. Adding a stacktace to errors?

There are a bunch of issues and inconveniences related to error-handling: 
1. Using different format for error codes and messages 
Sometimes errors are defined as package level variables and or custom error types, and sometimes they are just emanated just in-place by calling something like  
errors.New("Some error occurred")
2. Using different error-handling strategies 
In some cases we handle errors in-place by just logging them without passing them on,  in some other cases we just pass the errors on until they bubble up to the point they are caught by some middleware. Some errors are created without a stacktrace. Some errors that must not appear in the user response manage to do so carring some internal details which are in some cases are stripped out by our middleware. 
3. Using fragile tecniques to assert errors in tests 
There are a lot of places in our tests where an error is being asserted by a regular expression. It makes our tests fragile - if an error message or its format changes, the tests will fail. 
4. Using arcane and convoluted techniques to pass errors to API clients 
Some errors must be passed to client along with some additional data and the whole format  must respect JsonRPC spec. Some errors may contain sensitive data (logins/passwords, etc)

What I've been trying to say is that Error-handling is a good candidate for a Proposal which must be described and accepted before implementing...

When it comes to wrapping, it also must be decided how to eliminate over wrapping. Each wrap calls adds a lot of extra info  (including stacktrace on every call)

Wrapping errors must be done with great care. There must be a good guidance on how to do it properly, because there are quite a lot of pitfalls.

It's also important to keep it in mind that wrapping isn't free. It may heavily affect performance. Errors are omnipresent in go and adding some extra calls does have an impact on performance (up to 20% from my experience)

Talking about different contexts where errors are used:
1. Wrapping an external error (some other APIs and libraries, including stdlib) 
2. Emitting a new error that will be returned to API clients (Which error messages are shown to client and which are just logged)
3. Emitting an internal error which is used in a narrow scope and will not be returned to API clients
This case is primarily used by some validators which may have a list of errors representing diffirent states but at the latter end emitted as a single error.

I would suggest reading on the following (if it's not yet done of course), before deciding on how to address the problem :slightly_smiling_face:
* [Error handling and go] (https://blog.golang.org/error-handling-and-go)
* [Errors are values] (https://blog.golang.org/errors-are-values)
* [Inspecting errors] (https://dave.cheney.net/2014/12/24/inspecting-errors)
* [Constant errors] (https://dave.cheney.net/2016/04/07/constant-errors)

**Comment by oleg-raev** [comment]
@JekaMas 
>What task will be solved by just adding a context with wrapping?

I answered to @themue. My answer is not related to message from @divan 

>I think we need some kind of general solution as described above.

Absolutely

**Comment by oleg-raev** [comment]
>For example, in jail packages there are 36 checks for errors and only 14 pass error to the caller. 

Actually I found 33 of 49 (you are lost cases when happens error wrapping or err value checking at the line after condition) 
`grep -r 'err != nil' geth/jail/ | wc -l`
`grep -r -A3 "err != nil" geth/jail/ | grep -v "err != nil" | grep -i 'return.*err' | wc -l`

**Comment by tiabc** [comment]
Guys, thanks for sharing your opinion on the topic, your discussion has been really informative. I hope everything from your slack discussion is added here.

This issue appeared long ago when I stumbled upon a couple of nondescriptive error messages and tried to debug what's happening. And I created this issue as rather a reminder to look into error handling here.
Yesterday @oleg-raev asked me if could take the issue and my question was what exactly he could do and why and now I see there's no clear problem and a solution to that problem, let's hold on with this and get back when it gets a problem.
@oleg-raev please, try to pick something else.

**Comment by JekaMas** [comment]
Maxim made exactly same task for last two month in Lazada. I think his exp. could be relevant here.
