### ISSUE TITLE
Sub-accounts are not listed for eth_accounts call

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#294]
One of the side effects of #272 is that `AccountsListRequestHandler` isn't registered during `StatusBackend.registerHandlers` call: https://github.com/status-im/status-go/blob/9f57cf422f46dbd52a11bcc7971204b9d748ec4d/geth/api/backend.go#L208

Due to that our `eth_accounts` call processing won't trigger post processing for accounts and won't append sub-accounts.

Acceptance criteria:
1. There's a written test for this case.
2. Accounts and sub-accounts are listed on `eth_accounts` call.

**Comment by divan** [comment]
After some investigation, this issue has two overlapping possible reasons (in order of priority):

 - `eth_accounts` is being routed to the Upstream node instead of Local node.
 - our custom accounts filter handler is not registered (when `les` service is failed to start, doesn't matter for now)

The first one is due to existence of two different RPC client implementations (`RPCManager` and `RPCClient`). Routing (called ExecutionPolicy now) is implemented only in second, while `eth_accounts` call is using exposed `CallRPC` function, which use RPCManager.

The second one needs some deep refactoring of that handler coupling with `les` service, but it's not the root cause of the problem.
