### ISSUE TITLE
Devise how to update CHT automatically

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#320]
# Problem Overview

CHT stands for Canonical Hash Trie - a concept of go-ethereum allowing to start synchronisation from the last trusted state which we use to avoid overheating phones, long synchronisation time and battery drain.

Currently, CHT is embedded into status-go source code and it brings a number of problems:
1. We have to manually update CHT for every release.
2. As we release about twice a month, CHT gets more and more outdated.
3. Synchronisation time (and thus heating and battery drain) gets tangible for outdated versions.

# Implementation

The first step is to investigate how it can be achieved and there're some options:
1. A temporary and quick solution could be a dedicated server which will publish actual CHT values which our application will request for the most recent CHT before starting block synchronisation.
2. Implement and register another p2p protocol in go-ethereum stack.

# Acceptance Criteria

CHT is updated automatically before block synchronisation starts.

# Notes

I may be wrong but, as I remember, go-ethereum were going to make automatic CHT updates for les protocol.
There's a relevant issue about growing chaindata just to keep in mind: https://github.com/status-im/status-go/issues/277

**Comment by status-open-bounty** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 0.00
Contract address: [0x26332f5633a640821e42c5695dc1870df82d1708](https://etherscan.io/address/0x26332f5633a640821e42c5695dc1870df82d1708)
![QR Code](https://openbounty.status.im/qr/status-im/status-go/bounty/320/319e709b1651716d8a3042fc0ff036b0cbb58f8e0d0925c507e095c4effccd6e/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.

**Comment by pacamara** [comment]
Please note: per status team request, revised PR against upstream go-ethereum now addresses this issue instead:  https://github.com/ethereum/go-ethereum/pull/15673

**Comment by andytudhope** [comment]
Closing here as @pacamara has been rewarded out of band and will be working with Divan and Zsolt on LES2 for the rest of what is required.
