### ISSUE TITLE
Handle Batch JSON-RPC requests properly

### ISSUE THREAD

**Issue by oskarth** [status-im/status-go#333]
# Problem

Running latest `status-go` `develop` on `status-react` results in the following error: `MESSAGE: json: cannot unmarshal array into Go value of type rpc.jsonrpcMessage`. It was noticed when we upgraded to a newer version of `status-go` in https://github.com/status-im/status-react/pull/1584

Regression appears to have been introduced in https://github.com/status-im/status-go/commit/9a5c1774c3f9eeee748c283e5f07f5ad33e4bc28 since that is the only thing that touches RPC in the relevant commit range.

```
PRETTY PRINTED EXCEPTION

    ***
    NAME: "Error"
    MESSAGE: json: cannot unmarshal array into Go value of type rpc.jsonrpcMessage
```

**Comment by divan** [comment]
This error is because underlying Go RPC code expects JSON-RPC payload, but receives array with object. Error description is quite accurate.

Here are real example from logs (within the same session):

```
correct: {"jsonrpc":"2.0","id":6,"method":"shh_getFilterMessages","params":["2a9eb4505b621a44b0e0ed164eaf15db908e75d8824a3841cc2861ec6e9a4531"]}

incorrect: [{"jsonrpc":"2.0","id":7,"method":"shh_getFilterMessages","params":["2a9eb4505b621a44b0e0ed164eaf15db908e75d8824a3841cc2861ec6e9a4531"]}]
```

It's not clear why, but some payloads from `web3.js` comes in form of JSON objects, others - in form of array of objects.

In the original status-go jail code there is a code there seems to be handling similar situation: https://github.com/status-im/status-go/blob/8153d935d27fff88cd0a08b605b7a6dd8a059b90/geth/jail/jail.go#L166
This code is written back in the beginning of 2016 and there is no comments explaining the source of this issue.

One of the solutions is to handle the JSON-RPC in the similar way for `CallRPC()` function - try to unmarshal as object, and if failed, try again as an array.

**Comment by rasom** [comment]
This happens because `CallRPC` method doesn't handle batch RPC requests properly http://www.jsonrpc.org/specification#batch .
After fix introduced in https://github.com/status-im/status-go/pull/334 we have another error, response formatting for batch response is broken (it should be an array as in request):

```
Sep 18 09:59:57 MacBook-Pro-Roman StatusIm[54119]:
    payload:
     [{"jsonrpc":"2.0","id":8,"method":"shh_getFilterMessages","params":["f5b6f2778f3e47c60437239388c7020bbe93066c96ba7a3a673aebc9513b11b7"]}]
    response:
     {"jsonrpc":"2.0","id":8,"result":[]}
Sep 18 09:59:57 MacBook-Pro-Roman StatusIm[54119]: PRETTY PRINTED EXCEPTION

    ***
    NAME: "Error"
    MESSAGE: Invalid JSON RPC response: {"jsonrpc":"2.0","id":8,"result":[]}
```

**Comment by rasom** [comment]
Handling of batches in rpc calls in go-ethereum https://github.com/ethereum/go-ethereum/blob/a8eafcdc0e01ba1adcb25bfb0e06e7575c1a436e/rpc/json.go#L130

**Comment by divan** [comment]
Fixed in https://github.com/status-im/status-go/pull/341
