### ISSUE TITLE
Release Messenger After Local Pairing Has Completed

### ISSUE THREAD

**Issue by Samyoul** [status-im/status-go#3399]
During the Local Pairing process `backend.StartNodeWithAccount` is called:

```go
	activeAccount, _ := s.backend.GetActiveAccount()
	if activeAccount == nil { // not login yet
		s.backend.UpdateRootDataDir(nodeConfig.RootDataDir)
		// because client don't know keyUID before received data, we need help client to update keystore dir
		keystoreDir := filepath.Join(nodeConfig.KeyStoreDir, account.KeyUID)
		nodeConfig.KeyStoreDir = keystoreDir
		if accountPayload.exist {
			err = s.backend.StartNodeWithAccount(*account, accountPayload.password, nodeConfig)
		} else {
			accountManager := s.backend.AccountManager()
			err = accountManager.InitKeystore(filepath.Join(nodeConfig.RootDataDir, keystoreDir))
			if err != nil {
				return err
			}
			rmp.setting.InstallationID = nodeConfig.ShhextConfig.InstallationID
			rmp.setting.CurrentNetwork = settingCurrentNetwork

			err = s.backend.StartNodeWithAccountAndInitialConfig(*account, accountPayload.password, *rmp.setting, nodeConfig, rmp.subAccounts)
		}
		if err != nil {
			return err
		}
	}
```

This process effectively logs in the user. However, despite the Local Pairing process requiring a fully qualified instance of `Messenger`, the responsibility of Local Pairing should not be to log the application in **for the user**. Instead to maintain segregation of responsibility the Local Pairing process flow should clean up the logged in state of the application and log out once all Local Pairing functionality has completed. After the Local Pairing process flow the endpoint / application / user should choose to login.

The wider application should not have an expectation and/or rely on Local Pairing to guarantee a logged in state.

Consider the implications of :

- https://github.com/status-im/status-go/issues/3241
- https://github.com/status-im/status-go/issues/3304
- https://github.com/status-im/status-go/issues/3306

cc @igor-sirotin

**Comment by igor-sirotin** [comment]
Thanks Samuel!
Will just refer some points we discussed here:

1. These issues might be fixed by this change:
- https://github.com/status-im/status-desktop/issues/10312
- https://github.com/status-im/status-desktop/issues/10288
- https://github.com/status-im/status-desktop/issues/10097
- Can't change device name on Desktop after initial bootstraping (no issue reported here)

2. [Current desktop design](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=25869-518724&t=x6bbXRaXHzcuPSpj-4) has `Sign in` button.
With this change we will be able to follow the designs here.

![image](https://user-images.githubusercontent.com/25482501/232683463-25ed4a68-76a6-404d-ab0e-d960e2e3058d.png)

**Comment by igor-sirotin** [comment]
Also, this change will require desktop/mobile update.
I'm ready to first test it with desktop and then pass it to mobile team. Ping me anytime I'm needed 🙂
