### ISSUE TITLE
Mark intercepted `eth.SendTransaction()` with message-id

### ISSUE THREAD

**Issue by rasom** [status-im/status-go#34]
Roughly it means:
1) Check that `eth_sendTransaction` method is invoked there https://github.com/status-im/status-go/blob/47b01ec3c20746ae15fb7b46f347e2112dca411f/src/jail.go#L81-L81 (presumably by something like `call.Argument(0).Object().Get("method").toString() == "eth-sendTransaction"`)
2) Add `message-id` from `call.Otto.Context().Symbols["status"].Object().Get("message-id")` to parameters that will be sent via RPC (it is necessary to understand the structure of `call.Argument(0)` before)
3) Handle `message-id` on `eth.sendTransaction` request
4) Send signal with both `message-id` and `hash` to `status-react` when transaction is complete 

Need to be discussed.

**Comment by farazdagi** [comment]
Additional requirements:
- I need to implement queue, and *serialize* all the requests to a given VM (read on per chat level), before returning I also need to set context. Since calls are blocking, react-native will be able to get final value + context.
- here is sample code
```js
var context = {}

function addContext(key, value) {
  context[key] = value;
}

function call(pathStr, paramsStr) {
  var params = JSON.parse(paramsStr),
      path = JSON.parse(pathStr),
      fn, res;

  context = {};

  fn = path.reduce(function(catalog, name) {
    if (catalog && catalog[name]) {
      return catalog[name];
    }
  }, _status_catalog);

  if (!fn) {
    return null;
  }

  // while fn wll be executed
  // context will be populeted by
  // addContext calls from status-go
  callResult = fn(params)
  res = {
    result: callResult,
    // so context could contain
    // {transaction-sended: true}
    context: context
  };

  return JSON.stringify(res);
}
```


**Context:**
- we have `call` function in `status.js` https://github.com/status-im/status-react/blob/ccb2b4cf98ce6bca60e66816f0e2c7e63327caf6/resources/status.js#L47-L47, it is called here https://github.com/status-im/status-go/blob/edd8763c3c03a66f25eebbb6a4edeb0e528f5b34/jail/jail.go#L91-L91 and Roman wants to rewrite that `call` like:
https://gist.github.com/rasom/519517653ca593b05438d04230386336 (code is pasted above as well, for reference)
