### ISSUE TITLE
status-react should be able to depend on status-go develop

### ISSUE THREAD

**Issue by oskarth** [status-im/status-go#356]
# Problem

Currently, status-react can't depend on status-go `develop` being stable and not crashing the app.

Sometimes status-react has to depend on ad hoc branches in order to get the app to run or function in a desirable way. This also means progress/fixes made on status-go `develop` branch can't easily be incorporated, e.g. running the app in debug mode or exposing public API functions related to push notifications.

# Implementation

1) Make sure the app still starts OK before merging to develop.

2) Sometimes things will break on develop. When this happens, use fix-forward or revert commits when app breaks in severe ways on status-go develop.

3) There should be a last known good commit hash on develop branch which is very close to HEAD. To achieve this a more atomic upgrade commit might be necessary, and perhaps partial progress / abstractions can be merged earlier, and feature flags can be utilized to allow easy testing of experimental features/packages.

# Acceptance Criteria

- Solved when status-react don't have to think about 'develop' being in a broken state or not, other than incrementing a commit hash / staying put for an hour

- If develop is broken, announce a last known good commit hash and revert/fix-forward as if a branch is literally on fire

# Notes

See document on trunk-based development: https://docs.google.com/document/d/1lbSnTCVL9pu8qi_1wTOdXmalq1TJAPn2UlQfbIvUieI/edit#

# Future Steps

- status-react automatically depending on HEAD
- CI making sure app starts OK as automated end to end test

**Comment by oskarth** [comment]
Copy pasting from Slack thread to not lose history

**Comment by oskarth** [comment]
Copy pasting from Slack thread to not lost history:

@divan wrote:
> I think the major hindrance here is a way to verify if current develop breaks something or not. As far as I understand, that means running manual testing.
> 
> That's obviously not possible to do on each merge. (I still can't run status-react on my machine :confused: for example). 
> 
> One of the solutions is to automate this process and speed up as much as possible to make it run on CI. But I have no idea how feasible that would be. (I'm a big fan of automating everything that could be automated, though).

which @themue agreed with. @sla-shi pointed out that @adan is working on testing automation.

@divan I generally agree and think automated CI would be great. As a first step I don't think it is necessary to verify each commit to develop - this would be depending on HEAD. What do you think of point 2 and 3 in the issue?

I tried running our tests on a known failing status-go version and they all succeeded. We also have some kind of integration tests on status-react side (https://github.com/status-im/status-react/blob/develop/test/cljs/status_im/test/protocol/node.cljs and core.cljs) that could be triggered as part of the status-go CI step. I haven't managed to get these to actually run though. @roman knows more about this I think. If this is something status-react can do to help status-go help status-go, then we should make it a priority.

If we could clarify what class of fatal problems we can have - mismatch in data structure expectations, unclear semantics on sync/async, etc, we could do things to prevent these from happening (spec on cljs side, clarify contract and semantics systematically, etc). This should be part of a mini post mortem IMO.

Regardless we should get you all setup with a basic status-react environment. This is just as much prio as Clojure devs being able to run all devices they have access to. Otherwise it's like driving with one eye blindfolded.

On top of this the work @adan is doing with end to end UI automation tests would be very useful, but I don't think it should stop us from starting to address this idea. Furthermore, I think this type of UI automation (use status-go develop) check is the most important one, and should probably have priority over other types of UI automation tests (wallet integration, say).

**Comment by adambabik** [comment]
A few of my thoughts after reading this issue and the document that was mentioned on Slack:
1. status-react should not depend on status-go's develop branch. There should be another branch that is considered safe.
2. A branch is considered safe only if it passed automatic and manual e2e tests (on both simulators and real devices). However, it is safe only for **one specific** status-react commit because of no backward compatibility. 
3. Combining (1) and (2), safe branches must be in sync between repositories.
4. Safe branches should be created from develop branches. For instance, there is a new feature in status-react's develop branch. It should be tested against a safe status-go branch and only then merge to the status-react's safe branch.
5. Feature branches can be merged to develop after passing unit and integration tests (integration tests with testnets like Ropsten). Additionally, contract-based tests could also be incorporated, with a contract provided by status-react.

### What do these points solve?
1. Releases on-demand. As we have safe branches we can create a new release whenever we want. 
2. status-react can always have a safe branch to use in development, status-go alike.
3. Much clearer process for the Test Team.

### What don't these points solve?
1. Race conditions. It may happen that multiple combinations of the develop and safe branches are being tested. For instance, `go-safe-1` commit is tested with `react-develop-1` and `go-develop-2` with `react-safe-2`. Now, the first combination is merged and then the second one, but `go-develop-2` and `react-develop-1` may not work well with each other!
2. It may happen that changes in both repos are required and develop-develop combination needs to be tested. If so, the two branches must be merged at the same time.

All these ideas are not easy to be introduced right away. For now, my suggestion is that the status-go team gets a list of basic scenarios that they can perform using simulators. Feature branches that touch bindings, jail, transactions or the blockchain should be merged only after passing these scenarios.
