### ISSUE TITLE
SQL Scan for blobs receives string as input after the upgrade to SQLChipher

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-go#3590]
After the [SQLChipher upgrade](https://github.com/status-im/status-go/commit/e8c4b7647f67564c1d2b9534c8487202e91324d7) `Scan`, for BLOB objects, receive the input data as a string and [this](https://github.com/status-im/status-go/blob/9e0a12cb32bf8921ba7b5c923f743bb7119fab96/sqlite/fields.go#L21) cast to byte slice fails

I added a workaround to interpret the string as a byte slice in my PR here https://github.com/status-im/status-go/blob/17b3b78df1767f2dd67800e4494b2a9019d4a8f2/sqlite/fields.go#L32

**Comment by alexjba** [comment]
### There are a few culprits for this behaviour:

- `go-sqlcipher` will try to insert the data based on data types not column type. Ex: for `string` it will call `sqlite3_bind_text`; for `[]byte` `sqlite3_bind_blob`

- Sqlite is happy and proud that it can accept this. To quote sqlite docs:
> [Flexible typing is a feature](https://www.sqlite.org/flextypegood.html) of SQLite, not a bug

- Calling `Scan` will extract the data type from sqlite using [sqlite3_column_type](https://sqlite.org/c3ref/column_blob.html). It looks like `sqlite3_column_type` returns the data type stored in the DB, not the column data type. Not sure if this has changed somewhere between sqlite v3.20.1 and v3.41.2.

This is what sqlite allows:
<li style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box;"><center style="box-sizing: border-box;">

Column Datatype | Types Allowed In That Column
-- | --
INTEGER | INTEGER, REAL, TEXT, BLOB
REAL | REAL, TEXT, BLOB
TEXT | TEXT, BLOB
BLOB | INTEGER, REAL, TEXT, BLOB

</center></li><li style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box;"></li>

### We have a few options:

- Fix the `(blob *JSONBlob) Scan` to match the table above
- Allow `Flexible typing` on insert and use `Rigid typing` on select. One idea I have is to use [sqlite3_column_decltype](https://www.sqlite.org/c3ref/column_decltype.html) to determine the data type instead of `sqlite3_column_type`.
- Use [STRICT tables](https://www.sqlite.org/stricttables.html) to completely disable `Flexible typing`

**Comment by stefandunca** [comment]
Thanks, @alexjba for the findings. I didn't change the code of inserting strings in the test table in the meantime, therefore I suppose the update made the flexible typing work.

We have a few options:
> Fix the (blob *JSONBlob) Scan to match the table above
Not sure of interpreting BLOBS as integers and real numbers. We usually use the `JSONBlob` for json data. My workaround does the interpretation for a string which still makes sense.

It sounds to me that the current fix of allowing JSONBlob to accept `string` beside `byte[]`, given the JSON is text, matches flexible typing requirements and our type requirements. I propose to leave it as it is.

> Allow Flexible typing on insert and use Rigid typing on select. One idea I have is to use [sqlite3_column_decltype](https://www.sqlite.org/c3ref/column_decltype.html) to determine the data type instead of sqlite3_column_type.

Not sure at the moment of the side effects this change might have or if the benefits are worth it.

**Comment by alexjba** [comment]
> Not sure of interpreting BLOBS as integers and real numbers. We usually use the JSONBlob for json data. My workaround does the interpretation for a string which still makes sense.

You are right! I was preparing a PR to handle all the compatible data types for JSONBlob, but now I see it doesn't make much sense.

I was also looking for other custom `Scan` implementations we have and none of them raised any flags to me.

IMO this task can be closed.
