### ISSUE TITLE
sharding: featured communities

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-go#3961]
In https://github.com/status-im/status-go/pull/3944 sharding for communities is introduced. However the smart contract for featured communities does not take into account that a community might belong to a shard cluster/index. 
Once the smart contract is modified to include the required fields, we should modify  https://github.com/status-im/status-go/blob/272b1499b026198fb6224f7187b353f1c2a03add/protocol/messenger_communities.go#L562-L570 to include these. In the meantime to not make this a breaking change, the current behavior will be maintained and assume all communities are part of the default pubsub topic

cc: @jrainville

**Comment by richard-ramos** [comment]
Who updates the smart contract with the new shard information? :thinking:

**Comment by jrainville** [comment]
I know @osmaczko was the one that worked on this. He's on paternity leave for now, so maybe @0x-r4bbit can do it as he has knowledge of the contract already

**Comment by 0x-r4bbit** [comment]
This can certainly be done but it will have an impact on many contract APIs.
@richard-ramos this might be a stupid question, but can the same communityID exist in different shards?

Either way, if we need to add this information to the contract, then this is also information that needs to be provided by the DApp, when users create voting rooms. Possibly also when they vote.

Not sure what's the time horizon for this is, but depending on availability, this might take a bit of time.

**Comment by osmaczko** [comment]
We agreed to make the contracts shard-info agnostic. This is because if we change a community's shard, we would also need to update the contract, which would be very problematic.

As a result, we will need to develop a mechanism to retrieve shard information for a given community ID. One idea is to use a pubsub topic where the control node can publicly announce the shard information.

May be also relevant to: #3962
