### ISSUE TITLE
Implement a mechanism to retrieve shard information for a given community ID

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-go#4230]
As a result, we will need to develop a mechanism to retrieve shard information for a given community ID. One idea is to use a pubsub topic where the control node can publicly announce the shard information.

_Originally posted by @osmaczko in https://github.com/status-im/status-go/issues/3961#issuecomment-1785453710_

### QA Test Scenario Description
Scenario 1
1. 
2. 
Scenario 2
1. 
2.

**Comment by jrainville** [comment]
Just to be sure, the Owner token Deployer mechanism to validate that someone is the rightful owner of a community can also be used without the community description right?

I'm asking, because we need to be sure that the info about the community' shard needs to be validated, so it will be signed, either by the community key or the owner's key. And since we won't have the community description yet, we need to be sure that just having the community ID is enough to validate an Owner.

**Comment by osmaczko** [comment]
> Just to be sure, the Owner token Deployer mechanism to validate that someone is the rightful owner of a community can also be used without the community description right?

Yes, all we need is community id.

Currently, the trigger for owner validation is the `CommunityDescription` signed by an unverified user. This creates a chicken-and-egg problem: we can't validate shard information because we lack the signer's details, and we can't obtain the `CommunityDescription` since we don't have knowledge of the shard. However, this can be easily resolved by using `CommunityShardInfo` as an additional trigger for owner validation.
