### ISSUE TITLE
Limit the number of link previews

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-go#4236]
# Problem

Make the limit dumb for now, without any UI.
Basically, `UnfurlURLs` should only take first 20 links.
We should also cut any excess links on reception, if there's more than 20.

We can make the number smaller (e.g. 10), if it's required for mobile performance. But better to keep it high, because we won't have any UI warnings for now.

Original mobile issue here: https://github.com/status-im/status-mobile/issues/15908

**Comment by igor-sirotin** [comment]
OpehGraph standard for image size is `1200 * 630`. Some webseites like https://github.com and https://ethereum.org return images up to 300kb. Take 3 of such links and hit the waku envelope limit.

We should probably scale down these images to `303 * 170`, which is by [design](https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?type=design&node-id=22347-219536&mode=design&t=BW5wa1Cvu1oXcqFS-4) (it's `271*139` on [mobile](https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?type=design&node-id=22347-219536&mode=design&t=BW5wa1Cvu1oXcqFS-4), which is smaller).
Maybe consider taking `@2x` from this for high-res displays.

cc @ilmotta

**Comment by ilmotta** [comment]
> OpehGraph standard for image size is `1200 * 630`. Some webseites like https://github.com and https://ethereum.org return images up to 300kb. Take 3 of such links and hit the waku envelope limit.
> 
> We should probably scale down these images to `303 * 170`, which is by [design](https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?type=design&node-id=22347-219536&mode=design&t=BW5wa1Cvu1oXcqFS-4) (it's `271*139` on [mobile](https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?type=design&node-id=22347-219536&mode=design&t=BW5wa1Cvu1oXcqFS-4), which is smaller). Maybe consider taking `@2x` from this for high-res displays.
> 
> cc @ilmotta

Also linking to the issue I wrote some time ago, but in status-mobile https://github.com/status-im/status-mobile/issues/15909

This is a fairly interesting topic! status-go provides a mechanism for compressing JPEGs within a certain number of bytes.

https://github.com/status-im/status-go/blob/9d0acc2265bc19bbd3c5b6555ca538e678c7677f/images/encode.go#L74

Fully agree @igor-sirotin, we should definitely process all images persisted to waku because websites are giving us enormous images for the purposes of link previews (at least for small screens, mobile devices).

Besides the usual pixel density reduction and compression, the choice of format to persist should be seriously re-evaluated post-MVP. WebP, or better yet AVIF are superior formats than JPEG in a number of factors and can deliver significantly better images for the same size or much smaller images. The code for auto-compressing images in status-go only supports JPEG I believe. Android 12 supports AVIF https://developer.android.com/about/versions/12/features#avif and so does iOS 16, but I haven't checked any of them in practice. I suppose the Status desktop client could support these new formats just fine (in terms of lib support).

But anyway, image formats are another thread entirely. I just wanted to highlight our choice of image format is a big part of this puzzle in the search for improved efficiency at the waku layer.
