### ISSUE TITLE
Use postgresql for store persistence

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-go#4399]
Currently when the store node feature is enabled, we store the messages in the same sqlcipher DB of the user.
We should instead let the user specify a postgresql DB url and store the messages there. SQLite/SQLCipher will just not scale if the volume of messages is too high.

If we want to make the postgresql usage optional, we should at least use an sqlite database instead of reusing sqlcipher to reduce the overhead of db encryption

cc: @chair28980 @plopezlpz

### QA Test Scenario Description
Scenario 1
1. 
2. 
Scenario 2
1. 
2.

**Comment by plopezlpz** [comment]
Do not bundle it with the Desktop app, if the user has already a postgres instance running he could provide the connection string to use it @cammellos

**Comment by kaichaosun** [comment]
Andrea further clear the requirements with John, this issue is only for go-waku nodes on the fleet, and low priority. Should we move this issue to go-waku repo instead? @chair28980 @richard-ramos

**Comment by chaitanyaprem** [comment]
> Andrea further clear the requirements with John, this issue is only for go-waku nodes on the fleet, and low priority. Should we move this issue to go-waku repo instead? @chair28980 @richard-ramos

I don't think this has anything to with fleet nodes, this functionality is in status-go. @richard-ramos can confirm

**Comment by kaichaosun** [comment]
For the questions from @richard-ramos 
```
is it not wanted anymore to allow desktop act as a store node?
if that's the case, then the issue is no longer necessary, and we could remove the option to enable store protocol in desktop
```

@cammellos helps confirm that to store persistence issue is scoped to fleet nodes.

I will prepare the PR to remove the setting options for waku store in status-desktop.

**Comment by cammellos** [comment]
> For the questions from @richard-ramos
> 
> ```
> is it not wanted anymore to allow desktop act as a store node?
> if that's the case, then the issue is no longer necessary, and we could remove the option to enable store protocol in desktop
> ```
> 
> @cammellos helps confirm that to store persistence issue is scoped to fleet nodes.
> 
> I will prepare the PR to remove the setting options for waku store in status-desktop.

I don't know whether to be honest we don't want desktop to act as a store node, what I do know is that we don't need to have postgres for it, sqlite is perfectly fine and the best choice in case someone wants to run desktop as a store node. @John-44 might know what exactly is the desired behavior.

**Comment by chair28980** [comment]
@kaichaosun Based on conversation with @John-44 and @cammellos, it seems that Postgres is required solely for fleet store nodes, and not for client nodes. Given this, should we consider de-prioritizing or even closing this issue? cc @richard-ramos @plopezlpz

**Comment by John-44** [comment]
@chair28980 @cammellos @iurimatias @kaichaosun @fryorcraken @richard-ramos @plopezlpz Until Waku store nodes have awareness of what messages they store, what messages they don't store, and an ability to populate themselves from other store nodes (e.g. all the work required to make a large number of intermittently connected unreliable store nodes into a collectively reliable store node service), we really only want to have a **single** high availability high bandwidth store node db (connected to multiple store node heads) on the general Status Waku shard and per each community shard.

So for the time being, until we've built everything needed for individually unreliable store nodes to collectively provide a high reliability service, I think we should remove the ability for user's to set Status Desktop to act as a store node from the UI.  Because if a user enables this setting in Status Desktop, it would actually make the store node service on the Waku shards that Status uses *less* reliable!
