### ISSUE TITLE
Remove creating global catalog variable from status-go

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#450]
# Problem

During a jail cell creation and initialization, a JS code is executed that looks out of place:
```go
func (j *Jail) CreateAndInitCell(chatID string, code ...string) string {
  // create and init a cell...

  // this is inlined
  _, err := cell.Run(`var catalog = JSON.stringify(_status_catalog)`)
  if err != nil {
    return newJailErrorResponse(err)
  }

  // return `catalog` as string
}
```

As `_status_catalog` is not defined in status-go, this code should not be here as well.

# Implementation

~~When PR #401 is merged, there will be a new binding `ExecuteJS` which will allow running this JS code from status-react.~~

~~Prerequisite: contact status-react team before starting working on this and iron out the final details.~~

I talked to status-react team and we don't want to create `ExecuteJS` binding just for this detail. This binding should be removed. Instead, we want to return the last result of `cell.Run(js)` executed inside `Jail.createAndInitCell()` method.

# Acceptance Criteria

1. status-react team is aware of this change and committed to fixing it on their side,
1. JS code creating `catalog` variable is eliminated from status-go,
1. Tests that check `CreateAndInitCell` are fixed.

**Comment by rasom** [comment]
IMO we could skip extra `ExecuteJS` call, what if ~`Parse`~ `CreateAndInitCell ` will return the value which is returned by `cell.Run`? We can simply move this js to status-react side but still call only one method.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 4000.00
Contract address: [0x07a3b41a3fbda94c51eeee17064a8c81f9df7c60](https://etherscan.io/address/0x07a3b41a3fbda94c51eeee17064a8c81f9df7c60)
Network: Mainnet
Paid to: mandrigin
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by monokh** [comment]
I'd like to give this a go but wanted to clarify my understand of the issue and concepts.

- The jail is a sandboxed javascript context within the `status-go` node.
- The purpose of the jail is to access code that is available on the `status-go` side from the react app?
- The issue here is that status-go itself does not need to know about the specific use case of getting the catalog variable which could accomplished better by status-react calling `CreateAndInitCell` with the code to execute. 
- The fix is to change `CreateAndInitCell` to return evaluated variable of the last statement in the passed javascript code
- Currently the retrieval of catalog has been extracted into `makeCatalogVariable`. The main task is to remove this and ensure the app functions with the changes that `status-react` will also be making. 
- What actual part of the status product does this change effect? Just so I can have some context in mind.

**Comment by monokh** [comment]
Just noticed there already is an open PR for this 😅  Would be interested in the above questions still just out of curiosity. 

Also here's the way i was going about it if you were wondering: https://github.com/monokh/status-go/commit/235dd8f8271eb2cfb66c987354e3a68a2205b589
