### ISSUE TITLE
lib directory should not call flag.Parse

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#468]
# Problem

While working on https://github.com/status-im/ideas/issues/2, we need to build a library (c-archive) so that a native node.js module can be created. However, if any command line arguments are passed, the Go code tries to parse them and returns an error if they are not recognized. 

For example, `node --napi-modules ./test/binding_test.js` throws an error `flag provided but not defined: -napi-modules` (assume status-go is imported along the way as a native module). 

# Implementation

At least one file in `lib/` imports `testing/` package in which file `testing.go` calls `flag.Parse()`. It needs to be fixed so that `flag.Parse()` is not called when running any code from a library generated from `lib/`.

# Acceptance Criteria

1. `node --napi-modules ./test/binding_test.js` in repo https://github.com/status-im/status-node-ethereum/tree/napi-v8.2.1 runs successfully.

**Comment by divan** [comment]
The only reason why `lib` imports `flag` is because it imports `e2e/testing` package from `utils.go`. `utils.go`, in fact, contains just functions needed for testing, and it uses `cgo`, that's why it's not named `utils_test.go`. If you rename `utils.go` into `utils_test.go`, error will be thrown on build:

```
can't load package: package github.com/status-im/status-go/lib: use of cgo in test /Users/divan/src/github.com/status-im/status-go/lib/utils_test.go not supported
```

So, two thoughts:
 - if this issue is blocking N-API/Node.js wrappers task, just move `library_test.go` and `utils.go` somewhere and proceed without it.
 - we need to resolve cgo in testing issue, that will solve this problem properly
