### ISSUE TITLE
Flaky test: TestAdminBanMemberWithDeletingAllMessages

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-go#4842]
[TestAdminCommunityEventsSuite/TestAdminBanMemberWithDeletingAllMessages: 40.0% (8 of 20 failed)
](https://ci.status.im/job/status-go/job/tests-nightly/142/Reports/)

```
/home/jenkins/workspace/status-go/tests-nightly/protocol/communities_messenger_admin_test.go:360
        	Error:      	Received unexpected error:
        	            	MessengerResponse data not received
        	Test:       	TestAdminCommunityEventsSuite/TestAdminBanMemberWithDeletingAllMessages
```
https://ci.status.im/job/status-go/job/tests-nightly/142/testReport/github/com_status-im_status-go_protocol/TestAdminCommunityEventsSuite_TestAdminBanMemberWithDeletingAllMessages/

**Comment by mprakhov** [comment]
interesting... 
I see an error during waiting for a response:
{"error": "event sender: alice should be in the pending state"}
So Alice did not receive/apply the event

Could it be that due to our new event mechanism:
1. the client have a delay in receiving events?
2. response sent to the client faster than we store events in the db?
3. Do we have any other failed admin/TM tests (except my new ones)?

The code is the same as a simple ban, the only difference is that we send a message before banning, but we pass this check

**Comment by osmaczko** [comment]
> 1. the client have a delay in receiving events?

Wdym? events are sent straight away.

> 2. response sent to the client faster than we store events in the db?

What response exactly? Updated `CommunityDescription`? Not sure about it.

> 3. Do we have any other failed admin/TM tests (except my new ones)?

According to the [report](https://ci.status.im/job/status-go/job/tests-nightly/142/Reports/), I don't think so (except the ones already commented out long time ago).

**Comment by mprakhov** [comment]
ok, will take a look today.
from what I see from logs, what could have gone wrong, Alice:
a. did not receive Event
b. event failed and she did not store it in the DB
c. MessagenerResponse received earlier, that event was stored to the DB

Will check all scenarios

**Comment by mprakhov** [comment]
ok, the problem is that we are receiving 2 messages
1st - event
2nd - communityDescription update

We handle events and adding community to the response
After - we handled the community description (which removes our events as the community description was updated) and replaced the previous community in the response

When we request pending state in wait condition - it requires events, that were removed due to a previous community update
