### ISSUE TITLE
Automatically detect new flaky tests on PR level

### ISSUE THREAD

**Issue by Samyoul** [status-im/status-go#4952]
## Problems:

- As a developer, I want to be able to identify programmatically when a PR has introduced or altered an `integration` test, so that CI can target those tests for additional work.
- As a developer, I want CI to run validation tests on any new or altered `integration` test I introduce to this repo, so that these test runs are ensured by the CI and do not rely on flaky developer memory. 😄
  - See the Test Policy

## Dependant On

- https://github.com/status-im/status-go/issues/4935

## Ref:

https://github.com/status-im/status-go/pull/4908#discussion_r1520366773

**Comment by igor-sirotin** [comment]
To do this, we would need a separate coverage report for each test.
Then we should compare the PR diff against each test coverage and gather the list of affected tests.
Then we can run those tests with `-test.count=1000`. Since the number of affected tests can be a lot, we could limit the check to 1-2 hours.

The problem is that many PRs will affect a lot of tests. And we don't want many PRs to have 1-2 hours checks.

So I think it's this task is not realistic to implement. Also it's not simple in the first place.
Better to spend this time on automatic reporting of new flaky tests found in nightly runs.

Please reopen if you disagree, I don't have strong opinion on this.
