### ISSUE TITLE
CreateAndInitCell should allow reinitializing a cell

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#497]
# Problem

`CreateAndInitCell` is used to create and initialize a jail cell. It's also used to during bots development. If reinitializing is disabled, each code change requires restarting an app which is less than convenient.  

# Implementation

Do not throw an error when `Jail.CreateAndInitCell()` is called on an already existing cell.

A proposed solution is to rename the current `Jail.Parse` to `Jail.CreateAndInitCell` and replace references to `Jail.Parse` with `Jail.CreateAndInitCell`.

# Acceptance Criteria

1. `CreateAndInitiCell` binding allows being called multiple times with the same cell ID,
2. Consecutive `CreateAndInitiCell` calls with the same cell ID should not create new cells but reinitialize already existing one,
3. `Parse` binding in `library.go` is still present but it calls `statusAPI.CreateAndInitCell` for backward compatibility (unless the status-react team decides it can be removed).

# Future Steps

Remove `Parse` binding as its functionality will be exactly like `CreateAndInitCell` but `CreateAndInitCell` is more descriptive.

**Comment by canercidam** [comment]
I'm willing to work on this issue. Reading what `Jail.Parse` does, the logic seems unsafe regarding mutexes (can cause double creation) and looks like `Jail.CreateAndInitCell` was intended to solve that problem.

If keeping `Jail.createCell` and `Jail.CreateCell` is a must, something like `Jail.obtainCell` with a similar logic and no "already exists" error should fix it and an unsafe `Jail.createCellOnly` could be used to wrap actual cell creation.

Another option I can think of is setting error return value after checking a `unique ...bool` argument to `Jail.createCell`. How does it sound? Or also maybe changing it to `Jail.obtainCell` as well in this second case.

**Comment by adambabik** [comment]
> Reading what Jail.Parse does, the logic seems unsafe regarding mutexes (can cause double creation)

Do you mean double initialization? I don't think it's possible to override an already created cell in any way.

Also, I am not sure we need another method to create or get a cell. Feel free to change mutexes as maybe `createCell` does not need any but `CreateCell` and `CreateAndInitCell` should have it.

The most important here is that `CreateAndInitCell` creates a cell only if it does not exist but calls `initCell` always. `CreateAndInitCell` should be thread-safe.

**Comment by canercidam** [comment]
> Do you mean double initialization? I don't think it's possible to override an already created cell in any way.

You're right, my bad, double creation is not possible because of the second check in `Jail.createCell`. However, if there's any possibility of multiple concurrent calls to `Jail.Parse` happening with the same ID, it may cause undesired behaviour. In `Jail.Parse`, calling `Jail.cell` causes `Jail.cellsMx.RLock` to be called before a `Jail.cellsMx.Lock` call in `Jail.createCell` (which is in following `Jail.createAndInitCell` call):
```go
func (j *Jail) cell(chatID string) (*Cell, error) {
	j.cellsMx.RLock()
	defer j.cellsMx.RUnlock()
	...
}
```
```go
func (j *Jail) createCell(chatID string) (*Cell, error) {
	j.cellsMx.Lock()
	defer j.cellsMx.Unlock()
	...
}
```
Thus, two goroutines can get past `Jail.cell`, attempt to handle a non-nil error and go for `Jail.createAndInitCell` at the same time, then one of them would fail because of the second check here:
```go
func (j *Jail) createCell(chatID string) (*Cell, error) {
	...
	if cell, ok := j.cells[chatID]; ok {
		return cell, fmt.Errorf("cell with id '%s' already exists", chatID)
	}
	...
}
```
So `Jail.CreateAndInitCell` currently has a safer approach and renaming `Jail.Parse` shouldn't be an option IMHO. Using only `Lock` and doing both reading + writing as in `Jail.createCell` should be sufficient.

Can you please review PR #500 and see if it's a useful solution?

**Comment by adambabik** [comment]
@canercidam I reviewed #500 :) We will remove `Jail.Parse` eventually and your solution will allow status-react to transition to `Jail.CreateAndInitCell`.
