### ISSUE TITLE
Decouple suggestedRoutes from marketManager.FetchPrices

### ISSUE THREAD

**Issue by IvanBelyakoff** [status-im/status-go#5103]
# Problem

Currently in router's `suggestedRoutes` we call `marketManager.FetchPrices` to get fiat values and return them, but if market providers fail (conigecko, cryptocompare), we receive no routes error, though we actually can get routes, just not fiat values for the fees. We should separate the logic and make an extra call from client side for the fees values or at least do not consider market providers failure as a blocker error.

# Acceptance Criteria

Suggested routes must be returned independently of market providers

**Comment by saledjenic** [comment]
Closing cause this is not a relevant issue, since the router cannot work if we cannot fetch prices for tokens (also we did some improvements in that regard with having our proxy server and improved fallback logic for fetching prices).

The comparison we're using when searching for the best route needs prices for selected token + native token, so having prices is mandatory for the router.
@alaibe @IvanBelyakoff

**Comment by alaibe** [comment]
Mandatory for sure. I confirm

**Comment by IvanBelyakoff** [comment]
> Mandatory for sure. I confirm

@alaibe Could you please share why we can get the conversion rate from Uniswap for swaps, but can't use it for bridge?
So I mean we can return found routes to client without prices, then client requests to calculate the prices for the routes, which can call uniswap contracts (using our POKT/Infura RPC limits) to convert all the tokens to ETH and compare the prices in ETH.
If for some reason we fail (unsupported tokens?), we can try with cryptocompare/coingecko market providers.
If we fail again, we still display the routes, but we just dont know the cheapest one, user can select any suggested route.
I think it is a better solution architecturally and in terms of reliability as well.
Currently what we have: no prices? - no routes.

**Comment by alaibe** [comment]
@IvanBelyakoff AFAIK, Uniswap do not support all the tokens we do.

> So I mean we can return found routes to client without prices, then client requests to calculate the prices for the routes

That is a more complex UI suggestion than what we already have right?

We also display fees in dollar (well the currency selected by the user) and I think this is important to keep, so all in all we need to have the call for dollar right?

We could potentially try first to convert everything to eth and measure cost in eth, but still you need price of eth in dollar, so that is 2 conversion.
The direction is more to have a "simple" send which would need to simply convert ETH to USD for fees.

I feel we should more work toward having the capabilities to display price in currency rather than trying to avoid it as we need to convert in currency for assets view anyway.

**Comment by IvanBelyakoff** [comment]
> That is a more complex UI suggestion than what we already have right?

Yes, a bit more, not sure if we already fetch the fees separately on timeout, when user does not click "Send" for too long. Because in this case updating fees in fiat would not be different from what I suggest. So this seems to be the more flexile approach that will also server our other needs.

> We also display fees in dollar (well the currency selected by the user) and I think this is important to keep, so all in all we need to have the call for dollar right?
For me:
- having fees in fiat is better than not having fees in fiat
- having fees in ETH is better than not having fees at all
- having routes to make the transaction even without fiat fees is better than no routes

> We could potentially try first to convert everything to eth and measure cost in eth, but still you need price of eth in dollar, so that is 2 conversion.

The difference for us is that in most cases we will be dealing with tokens that are supported by uniswap (do we care that much about shit-coins?). We make calls to uniswap using our RPC providers, and we have agreements with them on amount of RPC requests, while we dont have agreements at the moment with market data providers and rely on their free plans.

>  feel we should more work toward having the capabilities to display price in currency rather than trying to avoid it as we need to convert in currency for assets view anyway.

I understand this, though I hope that with time ETH values for users will be as meaningful as fiat values, though currently it might be not the case. Also fees in percentage of the amount to transfer is very meaningful I believe.

Overall, this was my suggestion I believe we could benefit from, so that is why I raised the issue. Fine with me, if you dont find is useful.
