### ISSUE TITLE
Panic based on wrong error

### ISSUE THREAD

**Issue by themue** [status-im/status-go#516]
# Problem

In `status-go/geth/jail/internal/timers/timers.go` in function `Define()` a call to `call.Otto.ToValue(t)` returns the `setImmediateErr` (currently line 73).  The following `if` checks an outer `err` which is always `nil` then. The following `panic()`is never reached but raises `setImmediateErr` correctly.

# Implementation

Error check in `if` has to be the `setImmediateErr`.

# Acceptance Criteria

- [ ] Change the tested error
- [ ] Check if negative call of `call.Otto.ToValue(t)` is tested, otherwise add unit test
- [ ] Ensure CI is happy after changes

**Comment by pedropombeiro** [comment]
Hi @themue, I'm starting to look at this issue. Currently the anonymous method being passed to `setImmediate` isn't covered by tests, so that'd be the first thing. Regarding checking if the negative call of `call.Otto.ToValue(t)` is tested - do you mean testing the branch where `panic` is called? FWIW, that scenario isn't currently being tested for any of the other methods (`setTimeout`, `setInterval`). TBH I'm not sure what would be the scenario where `call.Otto.ToValue` would return an error, based on possible inputs from the unit test.
