### ISSUE TITLE
Research what is the purpose of async eviction loop in transaction queue

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#564]
# Problem

Right now the eviction behavior is not very clearly defined. For instance: 
- why it needs to run in the separate goroutine and evict tx every 250 ms?
- do we want to drop transactions that are in progress?
- why they are dropped silently?
- is it possible to get rid from eviction at all, and simply return an error if queue is full?

# Implementation

If we want to keep everything as it is - we need to comment the code so that every newcomer will be sure that the behavior is desired and not a legacy. But, more probable it is possible refactor eviction so that it will be clear to developers and users.

**Comment by ChrisSalisbury** [comment]
It looks like you are talking about the evict() function in the evictionLoop() method in this file: https://github.com/status-im/status-go/blob/develop/geth/transactions/queue/queue.go . 

Why it is in a separate channel and async is because it would otherwise block the calling process (hopefully this answers your todo on line 48). It is true that each calling process could start its own goroutine, but I think it makes more sense to just do it once in the method since that is probably the only use case anyone will need.

250 ms is certainly an arbitrary number, but it guarantees that at least 4 times every second, the transaction queue will be checked to make sure it isn't full. This number was likely arrived at empirically as a time somewhere more than half but less than the time it might typically take a queue to fill up so as not to poll too frequently nor too infrequently.

The comment on line 96 (and again on line 100) informs us that the evictionLoop method "frees up queue to accommodate another transaction item." This is required to ensure that hanging transactions don't multiply to infinite by a poor transaction generator or bad actor.

Within the loop, the transaction is checked in each of the cases given so that the transaction can end. Without this loop, the channel could go on forever. 

If the queue is full, and the transaction is dropped, it can be monitored in the transactions and inprogress fields. All of the logging can also be monitored. Returning an error from the evictionLoop would give very little additional benefit.

The eviction only occurs if the queue is full -- it's just a question of when the queue is checked. This could be refactored to avoid polling and to return errors rather than monitoring if errors are required, but the code would become more complicated, not less.



<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>status-go - The Status module that consumes go-ethereum</div></blockquote>
