### ISSUE TITLE
Sync blockchain before running e2e tests on public testnet

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#568]
# Problem

If e2e tests start on a public testnet and the blockchain is not synced, the tests fail due to timeout.

# Implementation

Have a prerequisite that checks if the blockchain is synced. If it's not, sync it before running e2e tests.

Instead of:
```
make test-e2e networkid=4
```

Do something like:
```
./build/bin/statusd -les -networkid 4 -exit-when-synced
make test-e2e networkid=4
```

This needs to be fixed in `.travis.yml`.

# Acceptance Criteria

1. E2e tests do not fail because of not synced blockchain.

**Comment by dshulyak** [comment]
I noticed that new blocks are created during tests, so it makes sense to sync the chain before every test suite or even test (like we do currently). Another problem - it won't be enough to run `go test`, so even if I want to run a single test I will have to run this prerequisite. It seems like a serious developer experience issue to me :).

**Comment by adambabik** [comment]
> I noticed that new blocks are created during tests, so it makes sense to sync the chain before every test suite or even test (like we do currently).

Correct but if the blockchain is synced in 95%, it will take a few seconds to sync the missing blocks during the test. 

> Another problem - it won't be enough to run go test, so even if I want to run a single test I will have to run this prerequisite. It seems like a serious developer experience issue to me :).

Yes and no but basically you need to know what you're doing. Preferably, developer should always run it on a private blockchain and if they want to run it on the public testnet, there must be a reason. Also, again, it's enough to sync it once and you will be good for a few hours as syncing the missing blocks will take a few seconds.

**Comment by adambabik** [comment]
Related #571

**Comment by dshulyak** [comment]
There are 2 options how it can be implemented.

1. This function can be reused https://github.com/status-im/status-go/blob/develop/testing/testing.go#L92-L145 after slight refactoring.

2. And there is second way that may provide better guarantees.

Following subscription can be used to track the progress of syncing: https://github.com/ethereum/go-ethereum/blob/master/eth/downloader/api.go#L93-L120 . But because we wrapped rpc client it will be required to add ethsubscribe method to it https://github.com/ethereum/go-ethereum/blob/master/rpc/client.go#L352-L355 . 

And the link to documentation what objects syncing subscription will return https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB#syncing

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>status-go - The Status module that consumes go-ethereum</div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/6250754?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/ethereum/go-ethereum">ethereum/go-ethereum</a></strong></div><div>go-ethereum - Official Go implementation of the Ethereum protocol</div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/6250754?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/ethereum/go-ethereum">ethereum/go-ethereum</a></strong></div><div>go-ethereum - Official Go implementation of the Ethereum protocol</div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/6250754?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/ethereum/go-ethereum">ethereum/go-ethereum</a></strong></div><div>go-ethereum - Official Go implementation of the Ethereum protocol</div></blockquote>

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 735.00
Contract address: [0xe77bda4ec84848f795bd95411140c2ef831bfdbd](https://etherscan.io/address/0xe77bda4ec84848f795bd95411140c2ef831bfdbd)
Network: Mainnet
Paid to: canercidam
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by canercidam** [comment]
Getting a PR ready for this.
