### ISSUE TITLE
Use configuration from a file for statusd daemon

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#614]
# Problem

The end goal is to have an ability to configure statusd using `docker config` [0] mechanism. We need to be able to control node parameters from tests and as we are using docker-compose for running a test cluster, docker config is optimal (and perhaps the only one) way to parametrize application without changing docker-compose.yml.

0. https://docs.docker.com/engine/swarm/configs/#how-docker-manages-configs

As you can see here https://github.com/status-im/status-go/blob/develop/_assets/compose/wnode-test-cluster/docker-compose.yml#L17, we won't be able to modify current configuration without modifying docker-compose.yml itself.

Additionally, the number of options that can be passed to statusd keeps increasing, so we want to have only the following options, and move the rest to the options file:
```
--help: Show usage
--version: Print version
--dumpcfg, -d: Dump configuration to stdout (can be redirected to a JSON file) and exits
--config FILE, -c FILE: Load configuration from FILE
--sync-and-exit MINUTES: Timeout in minutes for blockchain sync and exit, zero means no timeout unless sync is finished (default -1)
```

# Implementation

statusd uses `geth/params.NodeConfig` as a single source of configuration.

Regarding file format - let's stick to json, as we already have a `LoadNodeConfig` in `geth/params/config.go`

# Acceptance Criteria

It should be possible to:
- configure a status node with config file
- easily dump a node config to stdout or a file
- reading and dumping should be covered with unit tests

**Comment by divan** [comment]
My main concern with having config file is a need to deal with one more source of configuration, and we already have a few:
 - Defaults in `geth/params`
 - Configuration passed from status-react/status-desktop via `GenerateConfig()`
 - Command line flags

Now, by adding a configuration files, we need to make sure that order and priorities of those sources are crystal clear. 

If possible, I would ask which parameters we really need to configure from outside, and try to use command line flags for that. If the number of flags becomes too high, config file is a solution. If it's reasonable, I'd stick with command line flags only.

**Comment by mandrigin** [comment]
There are some config libraries that support 3 sources of configs: env, config file, command-line flags. We might wanna use one of those. That would provide some established standard of handling that and docs.

**Comment by dshulyak** [comment]
@divan without a config file it is not possible to parametrize docker-compose services. For instance, https://github.com/status-im/status-go/pull/609 - here I am experimenting with a different number of peers. Every time I have to change docker-compose, but with config file i will be able to generate one from golang, create `docker config` and use it for a statusd service.

I described motivation in the Problem section of this issue.

**Comment by mandrigin** [comment]
@dshulyak can we use `docker config` to set up command-line flags for the `statusd`?
like just call `./statusd $(./statusd-params.sh)` and specify `statusd-params.sh` in `docker config`? That would save us some go code.

**Comment by dshulyak** [comment]
@mandrigin yes, we can. but i am not a fan of such solutions. especially when they will not "save" us a lot. also if we are talking about preparing parameters from tests it is easier and more error-proof to dump json.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x8ac500132bde24d6343608cabe72fb3d0284c4544635caa3734bc89bfdb28fe2](https://etherscan.io/tx/0x8ac500132bde24d6343608cabe72fb3d0284c4544635caa3734bc89bfdb28fe2)

**Comment by PombeirP** [comment]
@dshulyak the link above is broken: https://github.com/status-im/status-go/blob/develop/docker/wnode-test-cluster/docker-compose.yml#L15

**Comment by sebastiandelgado** [comment]
@dshulyak I'm going to start working on this. Before I upload a WIP PR, I have a few questions:
 - Can I find the full list of configs that need to be added to `params.NodeConfig` in the output of `build/bin/statusd -h` or do I need to consider others?
 - When you say we will have to modify docker-compose.yml, are you talking about having it use the new `--config` flag you proposed above and then moving the rest of the config from the flags into the config file? Is there some other modifications you are proposing to docker-compose.yml?  
 - Given the conversation above, are we settled on using the config file as the single source of config? It makes sense to me, as in this case, we don't need to be worrying about the precedence of each different source of configuration. This is what I would do:
   - Remove all the other config flags
   - Have status-react/status-desktop use the config file somehow instead of using `GenerateConfig()` as it currently stands.
   - Move the geth/params/defaults.go to the default `params.NodeConfig` included in the repo
 - Will these changes be compatible with the `docker config` mechanism? What extra work will we need to do to integrate with dockers config?

How do you think we should split this up into multiple PRs? I'm thinking:
 - PR 1: Add the `--config` and `--dumpcfg` flags and have the config file override any defaults or command line configs, while still allowing other sources of configuration
 - PR 2: Remove command line flags and update docker-compose.yml
 - PR 3: Remove/Update `GenerateConfig()` so that status-desktop uses the config file as well
 - PR 4: Use the config file instead of defaults.go for defaults.

Let me know if you think we can split this issue into more PRs than this somehow. Would be easier to do it in a more granular way. Thanks for the help!

**Comment by dshulyak** [comment]
i don't think that we need config file anymore. for the following reasons:

1. in tests we won't rely on docker-compose and docker config, as that approach is less flexible than using direct docker api. so we will just use direct docker api and construct command line flags right from tests/go program

2. application is deployed using ansible (and will stay this way). and when ansible is used flags are quite flexible and we can do everything we need with them without config file

3. status-react (and i assume status-desktop) sends config as json when node is started (see bindings in /lib module) so this refactoring won't affect it in any way

4. and also we will have to rework significant part of tools to support config file, which is simply doesn't worth it for me atm

maybe it is better to get back to https://github.com/status-im/status-go/issues/761

**Comment by dshulyak** [comment]
i will close it for now to avoid confusion, if someone feels that we need config file please reopen
