### ISSUE TITLE
Create update-geth makefile target

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-go#668]
# Problem

As a follow up to https://github.com/status-im/status-go/pull/666, it would be nice to extract the procedure to update the `go-ethereum` dependency into a Makefile target (such as `update-geth`). This would simplify the `DEPENDENCIES.md` file and keep the procedure easily versioned (i.e. the user doesn't have to care if something in the procedure changed when he gets a newer branch).

# Implementation

Make a `update-geth` Makefile target that reproduces the instructions in https://github.com/status-im/status-go/blob/develop/_assets/docs/DEPENDENCIES.md.

# Acceptance Criteria

- There is a new `update-geth` target visible (with a help string) when running `make`.
- Running `make update-geth` will have the same effect as following the procedure in `DEPENDENCIES.md`
- `make update-geth` has a `branch` parameter for upgrading to new major releases
- The procedure in `DEPENDENCIES.md` is replaced with `make update-geth`

**Comment by alexkohler** [comment]
I'd like to take a stab at this! Should have a PR opened a little later.

**Comment by status-open-bounty** [comment]
Current balance: 0.000000 ETH
Contract address: [0x9d37ba31f4a76d02fd0f7c4722fbd3f8bd5402eb](https://ropsten.etherscan.io/address/0x9d37ba31f4a76d02fd0f7c4722fbd3f8bd5402eb)
![QR Code](http://7d1f0959.ngrok.io/qr/status-im/status-go/bounty/668/742a7e25e144aab731b71e9d5236813a3029d11be81fc02732a73973ad8d2d78/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [http://7d1f0959.ngrok.io](http://7d1f0959.ngrok.io) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
