### ISSUE TITLE
Fix e2e tests' race conditions

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-go#777]
# Problem

E2E tests are now run nightly with the `-race` flag. The build is [currently failing](https://jenkins.status.im/job/status-go/job/race-check/15/console).

```
==================
WARNING: DATA RACE
Write at 0x00c4217346f0 by goroutine 208:
  github.com/status-im/status-go/t/e2e/api_test.(*APIBackendTestSuite).TestRaceConditions.func9()
      /home/jenkins/workspace/status-go/race-check/src/github.com/status-im/status-go/geth/account/accounts.go:248 +0xf1

Previous read at 0x00c4217346f0 by goroutine 149:
  reflect.typedmemmove()
      /usr/local/go/src/runtime/mbarrier.go:259 +0x0
...
  github.com/status-im/status-go/t/e2e/api_test.(*APIBackendTestSuite).TestRaceConditions.func5()
      /home/jenkins/workspace/status-go/race-check/src/github.com/status-im/status-go/t/e2e/api/backend_test.go:85 +0x28f
```

# Implementation

We need to go over the failing tests and fix the root cause for the race condition.

# Acceptance Criteria

`make race-check` passes.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2200.00
Contract address: [0xf59a95def1f096d499df78f311e0b90ac019b15e](https://etherscan.io/address/0xf59a95def1f096d499df78f311e0b90ac019b15e)
Network: Mainnet
Paid to: adambabik
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by adambabik** [comment]
More insight into one group of failing tests. 

Try to run `go test -timeout 5m ./t/e2e/api/... -network=StatusChain -race`. This will fail because of `func (s *APIBackendTestSuite) TestRaceConditions()` and the fact that `s.T().Logf` is used which is not concurrent safe. The good solution here is to get rid of `func (s *APIBackendTestSuite) TestRaceConditions()` cimpletely and move it to unit tests. With a config creating an ephemeral `StatusNode`, it should not be hard.

More about ephemeral `StatusNode` can be found in this PR: https://github.com/status-im/status-go/pull/829.
