### ISSUE TITLE
NTP time source makes calls to the same ntp server

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#939]
# Problem

From the log 

```
ERROR[05-11|08:18:18] failed to compute offset                 error="RPC failed: read udp 172.17.0.5:40754->47.190.36.230:123: i/o timeout; read udp 172.17.0.5:38726->47.190.36.230:123: i/o timeout; read udp 172.17.0.5:35969->47.190.36.230:123: i/o timeout; read udp 172.17.0.5:37384->47.190.36.230:123: i/o timeout."
```

it is obvious that ntp client made calls to the same server `47.190.36.230:123:` , which should not be possible according to ntp documentation.

We need to find a way to prevent it from happening because it makes ntp time source less reliable.

# Implementation

One idea is to use different ntp pools, e.g 0.ntp.pool.org, 1.ntp.pool.org for every concurrent request

# Acceptance Criteria

All concurrent calls should be made to different NTP servers

**Comment by divan** [comment]
This problem essentially lays in the assumption that `pool.ntp.org` should always resolve to different NTP addresses, which turns out to be false for our use case. `pool.ntp.org` is a DNS load-balancer that returns up to 4 IP addresses of NTP servers geographically closest to you. While there is no precise information on NTPPool randomization algorithm (good luck reading [Perl source code](https://github.com/abh/ntppool) though), the [official page](http://www.pool.ntp.org/en/use.html) says that addresses are selected randomly that are "close to your country" and rotated hourly.

The probability that subsequent requests to `pool.ntp.org` will return the same IP is high (ntp pool resolver will often submit the same "closest to you" 4  IP addresses, and Go resolver will choose one of them from that pool). Plus, most Linuxes have some sort of internal DNS caching, which also may contribute to the the problem. I found that using native Go DNS resolver via `GODEBUG=netdns=go` (instead of CGo-based one), increases the chances to get different IPs. Also, results may differ from country to country (i.e. one country has move assigned servers in the ntp.pool database, than another)

So the viable solution seems to use `0.pool.ntp.org`, `1.pool.ntp.org`, `2.pool.ntp.org`, `3.pool.ntp.org` – they still may return the same IP address sometimes, but the probability is much lower.

**Comment by divan** [comment]
Also, official docs says that typical NTP update pattern should be `from once or twice a day to a 4-5 times an hour`. NTP Pool is a sort of volunteered project, and it's advised not to abuse the resources (i.e. spread out requests over timeframe with random offsets). So we might want to reconsider our current setting in 2-minute update interval.

Plus, it might be a viable option to join the NTP Pool project and run an own NTP server. See: http://www.pool.ntp.org/en/join.html

<blockquote><img src="/static/images/favicon.v717cb32.ico" width="48" align="right"><div><strong><a href="http://www.pool.ntp.org/en/join.html">pool.ntp.org: Join the NTP Pool!</a></strong></div></blockquote>
