### ISSUE TITLE
Mailserver to discard old messages

### ISSUE THREAD

**Issue by adriacidre** [status-im/status-go#948]
# Problem

Current mail server approach keeps messages stored forever, so the data volume growing is a real problem here.

# Implementation

Even we store messages forever, messages could be discarded after **N days(TBD)**.
A message garbage collector should be querying all messages older than **N days(TBD)** and remove them from the DB.

# Acceptance Criteria

- [x] Database does not grow indefinitely.

# Notes

This issue is part of #937

**Comment by adambabik** [comment]
@pilu Can you put some information how you want to implement it? I remember there was a discussion about preparing a separate command that could periodically do the maintenance. The problem is that it may not work if the other process using LevelDB is still running: https://github.com/google/leveldb/issues/182.

**Comment by gravityblast** [comment]
@adambabik yes, I was searching the same thing. I'm carrying on with the research and I'll write here a possible solution to be able to discuss it together.

**Comment by gravityblast** [comment]
@adambabik I think the best way is having a goroutine that prunes the database every N minutes so that we don't complicate the implementation given the problems on having multiple processes accessing the same db. In this PR (https://github.com/status-im/status-go/pull/949) @adriacidre already implemented a ticker to manage similar things so maybe we can use the same for this task.  

The only thing I want to see is benchmarking the deletion of messages to understand if it can slow down the server during the gc.
