### ISSUE TITLE
Pause node

### ISSUE THREAD

**Issue by farazdagi** [status-im/status-go#96]
- in order to preserve resources we need to completely stop the underlying Geth node
- there's a twist: we need to make sure that whatever account was selected when node was paused, gets re-selected when node resumes (including adding that account into Whisper)

**Comment by jarradh** [comment]
just to clarify, the reason we're trying this approach - is because the Android service appears to crash and we cannot seem to recover. 

We moved status-go out of a service and into the same process (similar what we do on iOS) but it's unacceptably slow. 

Our only known recourse is try to manage status-go in the service better and how this alleviates the issue.
