### ISSUE TITLE
Fix Jail requests when halting on long requests is enabled

### ISSUE THREAD

**Issue by farazdagi** [status-im/status-go#98]
- related #85 
- ~~the problem seems to be in blocking nature of `RunUnsafe()` (re-check whether it is problem in bindings code, or bug is in Otto's handling of `cancelInterrupt` channel)~~ well, current hypothesis is that problem is related to blocking `eth` calls on sync.

**Comment by influx6** [comment]
@tiabc  What's the status of this issue?

**Comment by tiabc** [comment]
@influx6, not sure what he meant. @jarradh, could you advise?

**Comment by tiabc** [comment]
Related to https://github.com/robertkrimen/otto#halting-problem
There's also an associated pull request: https://github.com/status-im/status-go/pull/103

@influx6, I'll add this issue to the next iteration. The task will be to find out what the problem was and fix it in the end.

**Comment by influx6** [comment]
@tiabc Awesome, thanks. Will await further orders.

**Comment by influx6** [comment]
@tiabc After going through the code within the PR #103, it seems they were faced with an occurance, similar to something i had faced where a otto vm call, could lead to a undetermined block, this was added to create a timeout which would be set when run to cancel the currently running calls with panics, since there was no way of doing so cleanly.

In my jugement, i believe part of the issue i faced which was related to fetch was properly due to loop, so am not really suspicious of otto right. I think we can close this for now or leave it open till we see any of the effects explained here in frequency.

For now, am very skeptic it is a problem for us to try fix or optimize for now.

**Comment by tiabc** [comment]
Closing due to @influx6's investigation.
